/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class forgett extends javax.swing.JFrame {

    /**
     * Creates new form forgett
     */
    public forgett() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        fname_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        male_rb = new javax.swing.JRadioButton();
        female_rb = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        lname_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dob_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        teacher_rb = new javax.swing.JRadioButton();
        admin_rb = new javax.swing.JRadioButton();
        student_rb = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 241, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 240, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 20, 220));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 240, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 240, 10));

        jLabel1.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, -1));

        fname_tf.setBackground(new java.awt.Color(238, 241, 247));
        fname_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        fname_tf.setForeground(new java.awt.Color(60, 60, 60));
        fname_tf.setBorder(null);
        fname_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fname_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fname_tfMouseExited(evt);
            }
        });
        fname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fname_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fname_tfFocusLost(evt);
            }
        });
        jPanel1.add(fname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 240, 40));

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Username");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        username_tf.setBackground(new java.awt.Color(238, 241, 247));
        username_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        username_tf.setForeground(new java.awt.Color(60, 60, 60));
        username_tf.setBorder(null);
        username_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                username_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                username_tfMouseExited(evt);
            }
        });
        username_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_tfFocusLost(evt);
            }
        });
        jPanel1.add(username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 40));

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Gender");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 150, -1));

        male_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup2.add(male_rb);
        male_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        male_rb.setText("Male");
        jPanel1.add(male_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        female_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup2.add(female_rb);
        female_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        female_rb.setText("Female");
        jPanel1.add(female_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 110, -1));

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Last Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 150, -1));

        lname_tf.setBackground(new java.awt.Color(238, 241, 247));
        lname_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        lname_tf.setForeground(new java.awt.Color(60, 60, 60));
        lname_tf.setBorder(null);
        lname_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lname_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lname_tfMouseExited(evt);
            }
        });
        lname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lname_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lname_tfFocusLost(evt);
            }
        });
        jPanel1.add(lname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 240, 40));

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Date of Birth");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 150, -1));

        dob_tf.setBackground(new java.awt.Color(238, 241, 247));
        dob_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        dob_tf.setForeground(new java.awt.Color(60, 60, 60));
        dob_tf.setBorder(null);
        dob_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dob_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dob_tfMouseExited(evt);
            }
        });
        dob_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dob_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dob_tfFocusLost(evt);
            }
        });
        jPanel1.add(dob_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 240, 40));

        jLabel5.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Select User Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 150, 30));

        teacher_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup1.add(teacher_rb);
        teacher_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        teacher_rb.setText("Teacher");
        jPanel1.add(teacher_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 100, 40));

        admin_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup1.add(admin_rb);
        admin_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        admin_rb.setText("Admin");
        jPanel1.add(admin_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 100, 40));

        student_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup1.add(student_rb);
        student_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        student_rb.setText("Student");
        jPanel1.add(student_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 90, 40));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Forget");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 120, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void fname_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fname_tfMouseEntered

    }//GEN-LAST:event_fname_tfMouseEntered

    private void fname_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fname_tfMouseExited

    }//GEN-LAST:event_fname_tfMouseExited

    private void fname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_tfFocusGained

    }//GEN-LAST:event_fname_tfFocusGained

    private void fname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_tfFocusLost

    }//GEN-LAST:event_fname_tfFocusLost

    private void username_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfMouseEntered

    private void username_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfMouseExited

    private void username_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfFocusGained

    private void username_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfFocusLost

    private void lname_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lname_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfMouseEntered

    private void lname_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lname_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfMouseExited

    private void lname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfFocusGained

    private void lname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfFocusLost

    private void dob_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfMouseEntered

    private void dob_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfMouseExited

    private void dob_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfFocusGained

    private void dob_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String fname="",lname="",user="",dob="",gender="",utype="";
fname=fname_tf.getText().toLowerCase();
lname=lname_tf.getText().toLowerCase();
user=username_tf.getText().toLowerCase();
dob=dob_tf.getText();
if(male_rb.isSelected()) gender="M";
if(female_rb.isSelected()) gender="F";
if(admin_rb.isSelected())
    utype="Admin";
else if(teacher_rb.isSelected())
    utype="Teacher";
else
    utype="Student";
//Fiels value Validation
if(fname.equals("")){
    JOptionPane.showMessageDialog(null, "Enter First Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
if(lname.equals("")){
    JOptionPane.showMessageDialog(null, "Enter last Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
if(user.equals("")){
    JOptionPane.showMessageDialog(null, "Enter Username Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
if(dob.equals("")){
    JOptionPane.showMessageDialog(null, "Enter Date of Birth.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}

//get password
PublicFunctions pf =new PublicFunctions();
pf.Query="Select lower(fname),lower(lname),dob,gender,mobile,pass,UserType from register where username = '"+user+"';";
pf.getrec();
try
{
    pf.r.next();
    if( fname.equals(pf.r.getString(1)) && lname.equals(pf.r.getString(2)) && dob.equals(pf.r.getString(3).replace("-", "")) && gender.equals(pf.r.getString(4)) && utype.equals(pf.r.getString(7)))
    {
            long num= Long.parseLong(JOptionPane.showInputDialog("Enter Your Mobile Number..!"));
                
            if( num==Long.parseLong(pf.r.getString(5)) ){
                JOptionPane.showMessageDialog(null, "Your Password is : \n\n"+pf.r.getString("pass"),"PASSWORD",JOptionPane.INFORMATION_MESSAGE);
                new login1().setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(null, "You Entered an Incorrect Number..!!!","ERROR",JOptionPane.ERROR_MESSAGE);
    }
    else
        JOptionPane.showMessageDialog(null, "Enter Correct Details..!!!","ERROR",JOptionPane.ERROR_MESSAGE);
}
catch(Exception e)
{
    int val=JOptionPane.showConfirmDialog(null, "User "+ user +" not Registered Yet..!\n\nIf you want to register yourself\nClick OK.!!","User not Exist",JOptionPane.YES_NO_OPTION);
    if(val==0)
    {
        new Register().setVisible(true);
        this.setVisible(false);
    }
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgett.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgett().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin_rb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField dob_tf;
    private javax.swing.JRadioButton female_rb;
    private javax.swing.JTextField fname_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lname_tf;
    private javax.swing.JRadioButton male_rb;
    private javax.swing.JRadioButton student_rb;
    private javax.swing.JRadioButton teacher_rb;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
