/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class login1 extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login1() {
        initComponents();
        this.setLocationRelativeTo(null); 
        jLabel7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        user_tf = new javax.swing.JTextField();
        pass_pf = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reg_lb = new javax.swing.JLabel();
        for_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 241, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_user_group_100px.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_user_male_20px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_key_20px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(27, 153, 229));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 260, -1));

        user_tf.setBackground(new java.awt.Color(238, 241, 247));
        user_tf.setFont(new java.awt.Font("GulimChe", 1, 20)); // NOI18N
        user_tf.setForeground(new java.awt.Color(27, 153, 229));
        user_tf.setText("Username");
        user_tf.setBorder(null);
        jPanel1.add(user_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 250, 40));

        pass_pf.setBackground(new java.awt.Color(238, 241, 247));
        pass_pf.setFont(new java.awt.Font("GulimChe", 1, 20)); // NOI18N
        pass_pf.setForeground(new java.awt.Color(27, 153, 229));
        pass_pf.setText("Password");
        pass_pf.setBorder(null);
        jPanel1.add(pass_pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 250, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 153, 229));
        jLabel5.setText("USER LOGIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(27, 153, 229));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_login_50px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 80, 80));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 153, 229));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Welcome to Attendance System");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 290, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(27, 153, 229));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_login_50px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 50, 60));

        reg_lb.setBackground(new java.awt.Color(0, 0, 0));
        reg_lb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        reg_lb.setForeground(new java.awt.Color(25, 118, 211));
        reg_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reg_lb.setText("Register");
        reg_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_lbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_lbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_lbMouseExited(evt);
            }
        });
        jPanel1.add(reg_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 90, -1));

        for_lb.setBackground(new java.awt.Color(0, 0, 0));
        for_lb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        for_lb.setForeground(new java.awt.Color(25, 118, 211));
        for_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        for_lb.setText("Forget Password ?");
        for_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        for_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                for_lbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                for_lbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                for_lbMouseExited(evt);
            }
        });
        jPanel1.add(for_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 140, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
jLabel9.setVisible(false);        
jLabel7.setVisible(true);   
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
      
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
jLabel7.setVisible(false);
jLabel9.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void reg_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseClicked
        this.setVisible(false);
        new Register().setVisible(true);
    }//GEN-LAST:event_reg_lbMouseClicked

    private void reg_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseEntered
        reg_lb.setForeground(new Color(39, 174, 96));
        reg_lb.setFont(new Font("Aparajita", Font.BOLD, 20));
    }//GEN-LAST:event_reg_lbMouseEntered

    private void reg_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseExited
        reg_lb.setForeground(new Color(27, 153, 229));
        reg_lb.setFont(new Font("Aparajita", Font.PLAIN, 18));
    }//GEN-LAST:event_reg_lbMouseExited

    private void for_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseEntered
        for_lb.setForeground(Color.red);
        for_lb.setFont(new Font("Aparajita", Font.BOLD, 19));
    }//GEN-LAST:event_for_lbMouseEntered

    private void for_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseClicked
        this.setVisible(false);
        new forgett().setVisible(true);
    }//GEN-LAST:event_for_lbMouseClicked

    private void for_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseExited
        for_lb.setForeground(new Color(27, 153, 229));
        for_lb.setFont(new Font("Aparajita", Font.PLAIN, 18));
    }//GEN-LAST:event_for_lbMouseExited

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
String user="",pass="";
user=user_tf.getText();
pass=pass_pf.getText();
if(user.equals("") || pass.equals("")){
JOptionPane.showMessageDialog(null, "Username and Password should not be Empty.!!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
PublicFunctions pf =new PublicFunctions();
pf.Query="Select pass,UserType from register where username = '"+user+"';";
pf.getrec();
try
{
    if(pf.r.next())
    {
        if(pass.equals(pf.r.getString("pass"))){
        if(pass.equals(pf.r.getString("pass")) && pf.r.getString(2).equals("Admin"))
        {
            new menu().setVisible(true);
            this.setVisible(false);
        }
        else if(pass.equals(pf.r.getString("pass")) && pf.r.getString(2).equals("Teacher"))
        {
            new TeacherMenu().setVisible(true);
            this.setVisible(false);
        }
        else if(pass.equals(pf.r.getString("pass")) && pf.r.getString(2).equals("Student"))
        {
            new view().setVisible(true);
            this.setVisible(false);
        }   }
        else
        {           
            JOptionPane.showMessageDialog(null, "Enter an valid Password","Wrong Password..!!",JOptionPane.ERROR_MESSAGE);
        }
    }
    else
    {
        int val=JOptionPane.showConfirmDialog(null, "User "+ user +" not Registered Yet..!\n\nIf you want to register yourself\nClick OK.!!","User not Exist",JOptionPane.YES_NO_OPTION);
        if(val==0)
        {
            new Register().setVisible(true);
            this.setVisible(false);
        }
    }
}
catch(Exception e){    
}
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel for_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField pass_pf;
    private javax.swing.JLabel reg_lb;
    private javax.swing.JTextField user_tf;
    // End of variables declaration//GEN-END:variables
}
