/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaurav
 */
public class manageuser extends javax.swing.JFrame {

    /**
     * Creates new form manageuser
     */
    public manageuser() {
        this.mobile = 0;
        initComponents();
        this.setLocationRelativeTo(null);
        update_bt.setEnabled(false);
        delete_bt.setEnabled(false);
        male_rb.setSelected(true);
        adm_rb.setSelected(true);
        getRecord();
    }
    PublicFunctions pf=new PublicFunctions();
   // user define functions  
    void getRecord()
    {
        pf.Query="Select * from Register;";
        try{
            pf.getrec();
            while(pf.r.next())
            {
                DefaultTableModel model= (DefaultTableModel) showrecords_tb.getModel();
                model.addRow(new Object[] {
                                            pf.r.getString(1),
                                            pf.r.getString(2),
                                            pf.r.getString(3),
                                            pf.r.getString(4),
                                            pf.r.getString(5),
                                            pf.r.getString(6),
                                            pf.r.getString(7),
                                            pf.r.getString(8),
                                            pf.r.getString(9),
                                            pf.r.getString(10)
                                          } );
            }
        }catch(Exception e){ JOptionPane.showMessageDialog(this, e); }
    }
    void emptyTable()
    {
        DefaultTableModel model= (DefaultTableModel) showrecords_tb.getModel();
        int row=showrecords_tb.getRowCount()-1;
        while(row>=0)
            model.removeRow(row--);
    }
    //global Declration
    String fname="",lname="",user="",pass="",gender="M",email="",add="",utype="";
    int  dob=0;
    long mobile;
    
    void getDataFromFrame()
    {
        fname=fname_tf.getText();
        lname=lname_tf.getText();
        user=username_tf.getText().toLowerCase();
        dob=Integer.parseInt(dob_tf.getText());
        mobile=Long.parseLong(mobile_tf.getText());
        if(male_rb.isSelected()) gender="M";
        if(female_rb.isSelected()) gender="F";
        email=email_tf.getText().toLowerCase();
        add=address_tf.getText().toLowerCase();
        pass=pass_tf.getText();
        if(adm_rb.isSelected())
           utype="Admin";
        else if(teacher_rb.isSelected())
            utype="Teacher";
        else
            utype="Student";
    }
    void setRecord()
    {
        add_bt.setEnabled(false);
        username_tf.setEditable(false);
        update_bt.setEnabled(true);
        delete_bt.setEnabled(true);
        clear_bt.setEnabled(true);
        DefaultTableModel model= (DefaultTableModel) showrecords_tb.getModel();
        int row=showrecords_tb.getSelectedRow();
        fname_tf.setText(model.getValueAt(row, 0).toString());
        lname_tf.setText(model.getValueAt(row, 1).toString());
        username_tf.setText(model.getValueAt(row, 2).toString());
        dob_tf.setText(model.getValueAt(row, 3).toString().replace("-", ""));
        String gen=(model.getValueAt(row, 4).toString());
        if(gen.equals("M")) male_rb.setSelected(true);
        if(gen.equals("F")) female_rb.setSelected(true);
        mobile_tf.setText(model.getValueAt(row, 5).toString());
        email_tf.setText(model.getValueAt(row, 6).toString());
        address_tf.setText(model.getValueAt(row, 7).toString());
        pass_tf.setText(model.getValueAt(row, 8).toString());
        String usertype=(model.getValueAt(row, 9).toString());
        if(usertype.equals("Admin")) adm_rb.setSelected(true);
        if(usertype.equals("Teacher")) teacher_rb.setSelected(true);
        if(usertype.equals("Student")) student_rb.setSelected(true);
    }
    void clearcode()
    {
        username_tf.setEditable(true);
        add_bt.setEnabled(true);
        update_bt.setEnabled(false);
        delete_bt.setEnabled(false);
        fname_tf.setText("");
        lname_tf.setText("");
        username_tf.setText("");
        dob_tf.setText("");
        male_rb.setSelected(true);
        mobile_tf.setText("");
        email_tf.setText("");
        address_tf.setText("");
        pass_tf.setText("");
        String usertype=("");
        adm_rb.setSelected(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        get_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        fname_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lname_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        male_rb = new javax.swing.JRadioButton();
        female_rb = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        address_tf = new javax.swing.JTextField();
        mobile_tf = new javax.swing.JTextField();
        dob_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        adm_rb = new javax.swing.JRadioButton();
        teacher_rb = new javax.swing.JRadioButton();
        student_rb = new javax.swing.JRadioButton();
        username_tf = new javax.swing.JTextField();
        pass_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        add_bt = new javax.swing.JButton();
        update_bt = new javax.swing.JButton();
        delete_bt = new javax.swing.JButton();
        clear_bt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showrecords_tb = new javax.swing.JTable();
        note_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 241, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        get_panel.setBackground(new java.awt.Color(238, 241, 247));
        get_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 118, 211), 2));
        get_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        get_panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 240, 10));
        get_panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 240, 10));
        get_panel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 240, 10));
        get_panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 240, 10));
        get_panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 240, 10));
        get_panel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 240, 10));
        get_panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        get_panel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 10, 320));
        get_panel.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 10));

        fname_tf.setBackground(new java.awt.Color(238, 241, 247));
        fname_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        fname_tf.setForeground(new java.awt.Color(60, 60, 60));
        fname_tf.setBorder(null);
        fname_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fname_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fname_tfMouseExited(evt);
            }
        });
        fname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fname_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fname_tfFocusLost(evt);
            }
        });
        get_panel.add(fname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 240, 40));

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Username");
        get_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jLabel1.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Name");
        get_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Last Name");
        get_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 150, -1));

        lname_tf.setBackground(new java.awt.Color(238, 241, 247));
        lname_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        lname_tf.setForeground(new java.awt.Color(60, 60, 60));
        lname_tf.setBorder(null);
        lname_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lname_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lname_tfMouseExited(evt);
            }
        });
        lname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lname_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lname_tfFocusLost(evt);
            }
        });
        get_panel.add(lname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 240, 40));

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Gender");
        get_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        male_rb.setBackground(new java.awt.Color(238, 241, 247));
        male_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        male_rb.setText("Male");
        get_panel.add(male_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, -1));

        female_rb.setBackground(new java.awt.Color(238, 241, 247));
        female_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        female_rb.setText("Female");
        get_panel.add(female_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 110, -1));

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Email");
        get_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 150, -1));

        email_tf.setBackground(new java.awt.Color(238, 241, 247));
        email_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        email_tf.setForeground(new java.awt.Color(60, 60, 60));
        email_tf.setBorder(null);
        email_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                email_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                email_tfMouseExited(evt);
            }
        });
        email_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                email_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                email_tfFocusLost(evt);
            }
        });
        get_panel.add(email_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 40));

        jLabel7.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Password");
        get_panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, -1));

        address_tf.setBackground(new java.awt.Color(238, 241, 247));
        address_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        address_tf.setForeground(new java.awt.Color(60, 60, 60));
        address_tf.setBorder(null);
        address_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                address_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                address_tfMouseExited(evt);
            }
        });
        address_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                address_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                address_tfFocusLost(evt);
            }
        });
        get_panel.add(address_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 240, 40));

        mobile_tf.setBackground(new java.awt.Color(238, 241, 247));
        mobile_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        mobile_tf.setForeground(new java.awt.Color(60, 60, 60));
        mobile_tf.setBorder(null);
        mobile_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mobile_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mobile_tfMouseExited(evt);
            }
        });
        mobile_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobile_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobile_tfFocusLost(evt);
            }
        });
        get_panel.add(mobile_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 240, 40));

        dob_tf.setBackground(new java.awt.Color(238, 241, 247));
        dob_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        dob_tf.setForeground(new java.awt.Color(60, 60, 60));
        dob_tf.setBorder(null);
        dob_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dob_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dob_tfMouseExited(evt);
            }
        });
        dob_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dob_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dob_tfFocusLost(evt);
            }
        });
        get_panel.add(dob_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 150, 40));

        jLabel5.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Date of Birth");
        get_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 150, -1));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Mobile");
        get_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 150, -1));

        jLabel10.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Address");
        get_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 170, -1));

        jLabel9.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Select User Type");
        get_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 130, -1));

        adm_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup1.add(adm_rb);
        adm_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        adm_rb.setText("Admin");
        get_panel.add(adm_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 70, 30));

        teacher_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup1.add(teacher_rb);
        teacher_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        teacher_rb.setText("Teacher");
        get_panel.add(teacher_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 80, 30));

        student_rb.setBackground(new java.awt.Color(238, 241, 247));
        buttonGroup1.add(student_rb);
        student_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        student_rb.setText("Student");
        get_panel.add(student_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 80, -1));

        username_tf.setBackground(new java.awt.Color(238, 241, 247));
        username_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        username_tf.setForeground(new java.awt.Color(60, 60, 60));
        username_tf.setToolTipText("");
        username_tf.setBorder(null);
        username_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                username_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                username_tfMouseExited(evt);
            }
        });
        username_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_tfFocusLost(evt);
            }
        });
        get_panel.add(username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 240, 40));

        pass_tf.setBackground(new java.awt.Color(238, 241, 247));
        pass_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        pass_tf.setForeground(new java.awt.Color(60, 60, 60));
        pass_tf.setBorder(null);
        pass_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pass_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pass_tfMouseExited(evt);
            }
        });
        pass_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_tfFocusLost(evt);
            }
        });
        get_panel.add(pass_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, 40));

        jLabel11.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("YYYYMMDD");
        get_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 110, -1));

        jPanel1.add(get_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 610, 370));

        jPanel3.setBackground(new java.awt.Color(238, 241, 247));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 118, 211), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add_bt.setBackground(new java.awt.Color(25, 118, 211));
        add_bt.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        add_bt.setForeground(new java.awt.Color(255, 255, 255));
        add_bt.setText("ADD");
        add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btActionPerformed(evt);
            }
        });
        jPanel3.add(add_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, -1));

        update_bt.setBackground(new java.awt.Color(25, 118, 211));
        update_bt.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        update_bt.setForeground(new java.awt.Color(255, 255, 255));
        update_bt.setText("UPDATE");
        update_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btActionPerformed(evt);
            }
        });
        jPanel3.add(update_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, -1));

        delete_bt.setBackground(new java.awt.Color(25, 118, 211));
        delete_bt.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        delete_bt.setForeground(new java.awt.Color(255, 255, 255));
        delete_bt.setText("DELETE");
        delete_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btActionPerformed(evt);
            }
        });
        jPanel3.add(delete_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 170, -1));

        clear_bt.setBackground(new java.awt.Color(25, 118, 211));
        clear_bt.setFont(new java.awt.Font("Aparajita", 1, 24)); // NOI18N
        clear_bt.setForeground(new java.awt.Color(255, 255, 255));
        clear_bt.setText("CLEAR");
        clear_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btActionPerformed(evt);
            }
        });
        jPanel3.add(clear_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 170, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 260, 300));

        jPanel4.setBackground(new java.awt.Color(238, 241, 247));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(25, 118, 211), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showrecords_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Username", "DOB", "Gender", "Mobile", "Email", "Address", "Password", "User Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showrecords_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showrecords_tbMouseClicked(evt);
            }
        });
        showrecords_tb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                showrecords_tbCaretPositionChanged(evt);
            }
        });
        showrecords_tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                showrecords_tbKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(showrecords_tb);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 890, 200));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 910, 220));

        note_lb.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        note_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note_lb.setText("<html><u>Note :<BR> </u>Username can not be update</html>");
        jPanel1.add(note_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 220, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void fname_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fname_tfMouseEntered

    }//GEN-LAST:event_fname_tfMouseEntered

    private void fname_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fname_tfMouseExited

    }//GEN-LAST:event_fname_tfMouseExited

    private void fname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_tfFocusGained

    }//GEN-LAST:event_fname_tfFocusGained

    private void fname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_tfFocusLost

    }//GEN-LAST:event_fname_tfFocusLost

    private void lname_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lname_tfMouseEntered

    }//GEN-LAST:event_lname_tfMouseEntered

    private void lname_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lname_tfMouseExited

    }//GEN-LAST:event_lname_tfMouseExited

    private void lname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_tfFocusGained

    }//GEN-LAST:event_lname_tfFocusGained

    private void lname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_tfFocusLost

    }//GEN-LAST:event_lname_tfFocusLost

    private void email_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_tfMouseEntered

    }//GEN-LAST:event_email_tfMouseEntered

    private void email_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_email_tfMouseExited

    }//GEN-LAST:event_email_tfMouseExited

    private void email_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_tfFocusGained

    }//GEN-LAST:event_email_tfFocusGained

    private void email_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_email_tfFocusLost

    }//GEN-LAST:event_email_tfFocusLost

    private void address_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_tfMouseEntered

    }//GEN-LAST:event_address_tfMouseEntered

    private void address_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_tfMouseExited

    }//GEN-LAST:event_address_tfMouseExited

    private void address_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_tfFocusGained

    }//GEN-LAST:event_address_tfFocusGained

    private void address_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_address_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_address_tfFocusLost

    private void mobile_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobile_tfMouseEntered

    }//GEN-LAST:event_mobile_tfMouseEntered

    private void mobile_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobile_tfMouseExited

    }//GEN-LAST:event_mobile_tfMouseExited

    private void mobile_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile_tfFocusGained

    }//GEN-LAST:event_mobile_tfFocusGained

    private void mobile_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobile_tfFocusLost

    }//GEN-LAST:event_mobile_tfFocusLost

    private void dob_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob_tfMouseEntered

    }//GEN-LAST:event_dob_tfMouseEntered

    private void dob_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob_tfMouseExited

    }//GEN-LAST:event_dob_tfMouseExited

    private void dob_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_tfFocusGained

    }//GEN-LAST:event_dob_tfFocusGained

    private void dob_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_tfFocusLost

    }//GEN-LAST:event_dob_tfFocusLost

    private void username_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfMouseEntered

    private void username_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfMouseExited

    private void username_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfFocusGained

    private void username_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfFocusLost

    private void pass_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfMouseEntered

    private void pass_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfMouseExited

    private void pass_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfFocusGained

    private void pass_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_tfFocusLost

    private void add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btActionPerformed
        try{
            getDataFromFrame();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Enter a Valid Birth Date or Mobile number.","Error",JOptionPane.INFORMATION_MESSAGE);return;
        }

        //Fileds Validation
        if(fname.equals("")){
            JOptionPane.showMessageDialog(null, "Enter First Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
        if(lname.equals("")){
            JOptionPane.showMessageDialog(null, "Enter last Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
        if(user.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Username Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
        if(pass.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Password.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}

        pf.Query="insert into register values('"+fname+"','"+lname+"','"+user+"',"+dob+",'"+gender+"',"+mobile+",'"+email+"','"+add+"','"+pass+"','"+utype+"')";
        pf.updtrec();
        JOptionPane.showMessageDialog(this, "New User added Sucessfully");
        emptyTable();
        getRecord();
    }//GEN-LAST:event_add_btActionPerformed

    private void update_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btActionPerformed
        try{
            getDataFromFrame();
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Enter a Valid Birth Date or Mobile number."+e,"Error",JOptionPane.INFORMATION_MESSAGE);return;
        }

        //Fileds Validation
        if(fname.equals("")){
            JOptionPane.showMessageDialog(null, "Enter First Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
        if(lname.equals("")){
            JOptionPane.showMessageDialog(null, "Enter last Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
        if(user.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Username Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
        if(pass.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Password.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}

        pf.Query="Update register set fname='"+fname+"', lname='"+lname+"', dob="+dob+", gender='"+gender+"', mobile="+mobile+", email='"+email+"', address='"+add+"', pass='"+pass+"', UserType='"+utype+"' where username='"+user+"';";
        pf.updtrec();
        JOptionPane.showMessageDialog(this, "Record Update Sucessfully");
        emptyTable();
        getRecord();
    }//GEN-LAST:event_update_btActionPerformed

    private void delete_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btActionPerformed
        int conf=JOptionPane.showConfirmDialog(null, "Do You Really want to delete \n\nUser : "+username_tf.getText(),"Confirm",JOptionPane.YES_NO_OPTION);
        if(conf==0){
            pf.Query="Delete from register where username='"+username_tf.getText().toLowerCase()+"';";
            pf.updtrec();
            JOptionPane.showMessageDialog(this, "Record Delete Sucessfully");
            emptyTable();
            getRecord();
            clearcode();
        }
    }//GEN-LAST:event_delete_btActionPerformed

    private void clear_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btActionPerformed
        clearcode();
    }//GEN-LAST:event_clear_btActionPerformed

    private void showrecords_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showrecords_tbMouseClicked
        setRecord();
    }//GEN-LAST:event_showrecords_tbMouseClicked

    private void showrecords_tbCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_showrecords_tbCaretPositionChanged

    }//GEN-LAST:event_showrecords_tbCaretPositionChanged

    private void showrecords_tbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showrecords_tbKeyReleased
        setRecord();       // TODO add your handling code here:
    }//GEN-LAST:event_showrecords_tbKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageuser().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_bt;
    private javax.swing.JTextField address_tf;
    private javax.swing.JRadioButton adm_rb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear_bt;
    private javax.swing.JButton delete_bt;
    private javax.swing.JTextField dob_tf;
    private javax.swing.JTextField email_tf;
    private javax.swing.JRadioButton female_rb;
    private javax.swing.JTextField fname_tf;
    private javax.swing.JPanel get_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lname_tf;
    private javax.swing.JRadioButton male_rb;
    private javax.swing.JTextField mobile_tf;
    private javax.swing.JLabel note_lb;
    private javax.swing.JTextField pass_tf;
    private javax.swing.JTable showrecords_tb;
    private javax.swing.JRadioButton student_rb;
    private javax.swing.JRadioButton teacher_rb;
    private javax.swing.JButton update_bt;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
