/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class selectsubject extends javax.swing.JFrame {

    /**
     * Creates new form selectsubject
     */
    public selectsubject() {
        initComponents();
    }
    String cname;
    int cyear,i;
    String[] scode;
    String cf_action;
    public selectsubject(String course_name, int yearsem,String action) {
        initComponents();
        cf_action=action;
        this.setLocationRelativeTo(null);   
        cname=course_name;
        cyear=yearsem;
        PublicFunctions pf =new PublicFunctions();
        try{
            pf.Query="select sname,scode from course c,course_details c1, subjects s where c.cid=c1.cid && s.ccys=c1.ccys && cname='"+cname+"' && year_sem="+cyear+" ";
            pf.getrec();
            pf.r.last();
            scode=new String[pf.r.getRow()];
            pf.r.beforeFirst();
            subject_cb.removeAllItems();
            i=0;
            while(pf.r.next()){
                subject_cb.addItem(pf.r.getString(1));
                scode[i++]=pf.r.getString(2);
            }
            scode_tf.setText(scode[0]);
            pf.Query="Select Date(Now())";
            pf.getrec();
            pf.r.next();
            D_T_lb.setText(pf.r.getString(1));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Subjects are not added to this course..!!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Subject_lb = new javax.swing.JLabel();
        subject_cb = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        test_lb = new javax.swing.JLabel();
        scode_tf = new javax.swing.JLabel();
        D_T_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 241, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        Subject_lb.setBackground(new java.awt.Color(255, 255, 255));
        Subject_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        Subject_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subject_lb.setText("Select Subject");
        jPanel1.add(Subject_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 350, 40));

        subject_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subject_cbItemStateChanged(evt);
            }
        });
        jPanel1.add(subject_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 30));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Sub Code : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        test_lb.setBackground(new java.awt.Color(255, 255, 255));
        test_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        test_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        test_lb.setText("Date ");
        jPanel1.add(test_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 40));

        scode_tf.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        scode_tf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scode_tf.setText("  ");
        jPanel1.add(scode_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));

        D_T_lb.setBackground(new java.awt.Color(255, 255, 255));
        D_T_lb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        D_T_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        D_T_lb.setText("1999-02-15 22:14:56");
        jPanel1.add(D_T_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String subname=subject_cb.getSelectedItem().toString();
String date=D_T_lb.getText();
if(cf_action.equals("add"))
   new add(cname,cyear,subname,date,scode_tf.getText()).setVisible(true);
if(cf_action.equals("update"))
   new update(cname,cyear,subname,scode_tf.getText()).setVisible(true);
if(cf_action.equals("delete"))
    new delete(cname,cyear,subname,scode_tf.getText()).setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void subject_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subject_cbItemStateChanged
scode_tf.setText(scode[subject_cb.getSelectedIndex()]);
    }//GEN-LAST:event_subject_cbItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectsubject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel D_T_lb;
    private javax.swing.JLabel Subject_lb;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel scode_tf;
    private javax.swing.JComboBox subject_cb;
    private javax.swing.JLabel test_lb;
    // End of variables declaration//GEN-END:variables
}
