/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class select_course_yearsem extends javax.swing.JFrame {

    /**
     * Creates new form select_course_yearsem
     */
    int tot=0,i=0;
    int[] max_yearsem;
    String[] course_type;
    String cf_action;
    public select_course_yearsem() {
        initComponents();
    }
    public select_course_yearsem(String action) {
        initComponents();
        cf_action=action;
        this.setLocationRelativeTo(null);
        PublicFunctions pf =new PublicFunctions();
        try{
            pf.Query="select count(*) from course";
            pf.getrec();
            pf.r.next();
            tot=Integer.parseInt(pf.r.getString(1));    //get total no of courses
            max_yearsem=new int[tot];
            course_type=new String[tot];
            pf.Query="select c.cname, max(c1.year_sem),ctype from course c,course_details c1 where c.cid=c1.cid group by cname";
            pf.getrec(); 
            while(pf.r.next())
            {
                course_cb.addItem(pf.r.getString(1));
                max_yearsem[i]=Integer.parseInt(pf.r.getString(2));
                course_type[i]=pf.r.getString(3);
                i++;
                if(max_yearsem[0]>=i)   yearsem_cb.addItem(i);
            }
            year_lb.setText("Select "+course_type[0]);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        course_lb = new javax.swing.JLabel();
        course_cb = new javax.swing.JComboBox();
        year_lb = new javax.swing.JLabel();
        yearsem_cb = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 241, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        course_lb.setBackground(new java.awt.Color(255, 255, 255));
        course_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        course_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        course_lb.setText("Select Course");
        jPanel1.add(course_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

        course_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                course_cbItemStateChanged(evt);
            }
        });
        jPanel1.add(course_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 30));

        year_lb.setBackground(new java.awt.Color(255, 255, 255));
        year_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        year_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year_lb.setText("Select");
        jPanel1.add(year_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 40));

        yearsem_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearsem_cbItemStateChanged(evt);
            }
        });
        yearsem_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsem_cbActionPerformed(evt);
            }
        });
        yearsem_cb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                yearsem_cbInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel1.add(yearsem_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(444, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void course_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_course_cbItemStateChanged
        int seleted_course=course_cb.getSelectedIndex();
        yearsem_cb.removeAllItems();
        year_lb.setText("Select "+course_type[seleted_course]);
        for(int i=1;i<=max_yearsem[seleted_course];i++)
        {
            yearsem_cb.addItem(i);
        }
    }//GEN-LAST:event_course_cbItemStateChanged

    private void yearsem_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearsem_cbItemStateChanged

    }//GEN-LAST:event_yearsem_cbItemStateChanged

    private void yearsem_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsem_cbActionPerformed

    }//GEN-LAST:event_yearsem_cbActionPerformed

    private void yearsem_cbInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_yearsem_cbInputMethodTextChanged

    }//GEN-LAST:event_yearsem_cbInputMethodTextChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String course_name=course_cb.getSelectedItem().toString();
int yearsem=Integer.parseInt(yearsem_cb.getSelectedItem().toString());
new selectsubject(course_name, yearsem,cf_action).setVisible(true);
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_course_yearsem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox course_cb;
    private javax.swing.JLabel course_lb;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel year_lb;
    private javax.swing.JComboBox yearsem_cb;
    // End of variables declaration//GEN-END:variables
}
