/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaurav
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    int id;
    PublicFunctions pf_global=new PublicFunctions();    
    public view() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTabbedPane1.setEnabledAt(1, false);
        jRadioButton1.setSelected(true);
        showrecords_tb.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
void emptyTable( javax.swing.JTable tb_name)
    {
        DefaultTableModel model= (DefaultTableModel) tb_name.getModel();
        int row=tb_name.getRowCount()-1;
        while(row>=0)
            model.removeRow(row--);
    }
void dis()
{    
try
{    
    pf_global.getrec();
    emptyTable(at);    
    DefaultTableModel model= (DefaultTableModel) at.getModel();
    while(pf_global.r.next())
    {
        model.addRow(new Object[] {
            pf_global.r.getString(1),
            pf_global.r.getString(2),
            pf_global.r.getString(3),
            pf_global.r.getString(4)
        } );        
    }
    jTabbedPane1.setSelectedIndex(1);
    st();
}catch(Exception e){}
}
void st()
{
    int present=0,absent=0;
for(int i=0;i<at.getRowCount();i++)
{
    if(at.getValueAt(i, 3).toString().equals("P"))
        present++;
    else
        absent++;
}
tot_lb.setText(""+at.getRowCount());
pr_ab.setText(present+"  /  "+absent);
float per=(present*100)/at.getRowCount();
per_lb.setText(per+" % ");
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        search_tf = new javax.swing.JTextField();
        searchby_cb = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showrecords_tb = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        sname_tf1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        at = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tot_lb = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pr_ab = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        per_lb = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        D_dd = new javax.swing.JComboBox();
        D_mm = new javax.swing.JComboBox();
        D_yy = new javax.swing.JComboBox();
        M_mm = new javax.swing.JComboBox();
        Y_yy = new javax.swing.JComboBox();
        M_yy = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        sub = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_cancel_35px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 241, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 230, 10));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Search By : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, -1));

        search_tf.setBackground(new java.awt.Color(238, 241, 247));
        search_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        search_tf.setForeground(new java.awt.Color(25, 118, 211));
        search_tf.setBorder(null);
        search_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_tfMouseExited(evt);
            }
        });
        search_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_tfFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_tfFocusGained(evt);
            }
        });
        search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_tfKeyReleased(evt);
            }
        });
        jPanel1.add(search_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 230, 40));

        searchby_cb.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        searchby_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admno", "Name" }));
        jPanel1.add(searchby_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        jButton1.setBackground(new java.awt.Color(25, 118, 211));
        jButton1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, 40));

        jTabbedPane1.setBackground(new java.awt.Color(238, 241, 247));
        jTabbedPane1.setForeground(new java.awt.Color(25, 118, 211));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(238, 241, 247));

        showrecords_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adm no", "Full Name", "Gender", "DOB", "Course", "Year/Sem", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showrecords_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showrecords_tbMouseClicked(evt);
            }
        });
        showrecords_tb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                showrecords_tbCaretPositionChanged(evt);
            }
        });
        showrecords_tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                showrecords_tbKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(showrecords_tb);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Show Record", jPanel3);

        jPanel6.setBackground(new java.awt.Color(238, 241, 247));

        jPanel7.setBackground(new java.awt.Color(238, 241, 247));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sname_tf1.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        sname_tf1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sname_tf1.setText("  ");
        jPanel7.add(sname_tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        at.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Subject", "Year_sem", "Attendance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(at);
        at.getColumnModel().getColumn(0).setResizable(false);
        at.getColumnModel().getColumn(1).setResizable(false);
        at.getColumnModel().getColumn(2).setResizable(false);
        at.getColumnModel().getColumn(3).setResizable(false);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 440, 250));

        jLabel11.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Total Days : ");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 20));

        tot_lb.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        tot_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel7.add(tot_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 160, 20));

        jLabel15.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Present / Absent : ");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 20));

        pr_ab.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        pr_ab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel7.add(pr_ab, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 160, 20));

        jLabel16.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Attendance per : ");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 20));

        per_lb.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        per_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel7.add(per_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 70, 20));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel7.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 10, 280));

        jLabel9.setFont(new java.awt.Font("Aparajita", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Filter :");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 160, 20));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Show all ");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });
        jPanel7.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Select Date");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });
        jPanel7.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, 30));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setText("Select Year");
        jRadioButton4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton4ItemStateChanged(evt);
            }
        });
        jPanel7.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 30));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setText("Select Month");
        jRadioButton3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton3ItemStateChanged(evt);
            }
        });
        jPanel7.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 30));

        D_dd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        D_dd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        D_dd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                D_ddItemStateChanged(evt);
            }
        });
        jPanel7.add(D_dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 50, -1));

        D_mm.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        D_mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        D_mm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                D_mmItemStateChanged(evt);
            }
        });
        jPanel7.add(D_mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 50, -1));

        D_yy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        D_yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        D_yy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                D_yyItemStateChanged(evt);
            }
        });
        jPanel7.add(D_yy, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 60, -1));

        M_mm.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        M_mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel7.add(M_mm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 50, -1));

        Y_yy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Y_yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        jPanel7.add(Y_yy, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 60, -1));

        M_yy.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        M_yy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2018", "2019", "2020", "2021", "2022" }));
        jPanel7.add(M_yy, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 60, -1));

        jButton2.setBackground(new java.awt.Color(25, 118, 211));
        jButton2.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Filter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 100, 30));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton5.setText("Select Subject");
        jRadioButton5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton5ItemStateChanged(evt);
            }
        });
        jPanel7.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, 30));

        sub.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jPanel7.add(sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 140, 30));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Show", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 670, 380));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(755, Short.MAX_VALUE)
                .addComponent(jLabel3))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void search_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfMouseEntered

    private void search_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfMouseExited

    private void search_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfFocusLost

    private void search_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfFocusGained

    private void search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_tfKeyReleased

    }//GEN-LAST:event_search_tfKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(search_tf.getText().equals(""))
        return;
        PublicFunctions pf=new PublicFunctions();
        try{
            pf.Query="Select Admno,name,gender,dob,course,year_sem,status from Student where "+searchby_cb.getSelectedItem().toString()+" like '%"+search_tf.getText()+"%';";
            pf.getrec();
            emptyTable(showrecords_tb);
            DefaultTableModel model= (DefaultTableModel) showrecords_tb.getModel();
            while(pf.r.next())
            {
                model.addRow(new Object[] {
                    pf.r.getString(1),
                    pf.r.getString(2),
                    pf.r.getString(3),
                    pf.r.getString(4),
                    pf.r.getString(5),
                    pf.r.getString(6),
                    pf.r.getString(7)
                } );
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erroe while setting table data into form"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void showrecords_tbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showrecords_tbKeyReleased

    }//GEN-LAST:event_showrecords_tbKeyReleased

    private void showrecords_tbCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_showrecords_tbCaretPositionChanged

    }//GEN-LAST:event_showrecords_tbCaretPositionChanged

    private void showrecords_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showrecords_tbMouseClicked
id=Integer.parseInt(showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 0).toString());
pf_global.Query="Select Date_of_at,s.sname,year_sem,status from attendance a, subjects s where a.scode=s.scode && a.admno="+id;
dis();
String cname,cyear;
cname=showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 4).toString();
cyear=showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 5).toString();
PublicFunctions pf1 =new PublicFunctions();
        try{
            pf1.Query="select sname,scode from course c,course_details c1, subjects s where c.cid=c1.cid && s.ccys=c1.ccys && cname='"+cname+"' && year_sem="+cyear+" ";
            pf1.getrec();
            while(pf1.r.next())
                sub.addItem(pf1.r.getString(1));
        }catch(Exception e){}
    }//GEN-LAST:event_showrecords_tbMouseClicked

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
if(jRadioButton1.isSelected())
{
    D_dd.setEnabled(false);
    D_mm.setEnabled(false);
    D_yy.setEnabled(false);
    M_mm.setEnabled(false);
    M_yy.setEnabled(false);
    Y_yy.setEnabled(false);
    sub.setEnabled(false);
}
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
if(jRadioButton2.isSelected())
{
    D_dd.setEnabled(true);
    D_mm.setEnabled(true);
    D_yy.setEnabled(true);
    M_mm.setEnabled(false);
    M_yy.setEnabled(false);
    Y_yy.setEnabled(false);
    sub.setEnabled(false);
}
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void D_ddItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_D_ddItemStateChanged

    }//GEN-LAST:event_D_ddItemStateChanged

    private void D_mmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_D_mmItemStateChanged
    // TODO add your handling code here:
    }//GEN-LAST:event_D_mmItemStateChanged

    private void D_yyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_D_yyItemStateChanged
    // TODO add your handling code here:
    }//GEN-LAST:event_D_yyItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(jRadioButton1.isSelected())
{
    pf_global.Query="Select Date_of_at,s.sname,year_sem,status from attendance a, subjects s where a.scode=s.scode && a.admno="+id;
    dis();
}
if(jRadioButton2.isSelected())
{
    String date=D_yy.getSelectedItem().toString()+D_mm.getSelectedItem().toString()+D_dd.getSelectedItem().toString();
    pf_global.Query="Select Date_of_at,s.sname,year_sem,status from attendance a, subjects s where a.scode=s.scode && a.admno="+id+" && Date_of_at="+date;
    dis();
}
if(jRadioButton3.isSelected())
{
    String date=M_yy.getSelectedItem().toString()+"-"+M_mm.getSelectedItem().toString()+"-%";
    pf_global.Query="Select Date_of_at,s.sname,year_sem,status from attendance a, subjects s where a.scode=s.scode && a.admno="+id+" && Date_of_at like '"+date+"'";
    dis();
}
if(jRadioButton4.isSelected())
{
    String date=Y_yy.getSelectedItem().toString()+"-%";
    pf_global.Query="Select Date_of_at,s.sname,year_sem,status from attendance a, subjects s where a.scode=s.scode && a.admno="+id+" && Date_of_at like '"+date+"'";
    dis();
}
if(jRadioButton5.isSelected())
{
    String Subject=sub.getSelectedItem().toString();
    pf_global.Query="Select Date_of_at,s.sname,year_sem,status from attendance a, subjects s where a.scode=s.scode && a.admno="+id+" && s.sname='"+Subject+"'";
    dis();
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton3ItemStateChanged
if(jRadioButton3.isSelected())
{
    D_dd.setEnabled(false);
    D_mm.setEnabled(false);
    D_yy.setEnabled(false);
    M_mm.setEnabled(true);
    M_yy.setEnabled(true);
    Y_yy.setEnabled(false);
    sub.setEnabled(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ItemStateChanged

    private void jRadioButton4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton4ItemStateChanged
if(jRadioButton4.isSelected())
{
    D_dd.setEnabled(false);
    D_mm.setEnabled(false);
    D_yy.setEnabled(false);
    M_mm.setEnabled(false);
    M_yy.setEnabled(false);
    Y_yy.setEnabled(true);
    sub.setEnabled(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ItemStateChanged

    private void jRadioButton5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton5ItemStateChanged
 if(jRadioButton5.isSelected())
{
    D_dd.setEnabled(false);
    D_mm.setEnabled(false);
    D_yy.setEnabled(false);
    M_mm.setEnabled(false);
    M_yy.setEnabled(false);
    Y_yy.setEnabled(false);
    sub.setEnabled(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox D_dd;
    private javax.swing.JComboBox D_mm;
    private javax.swing.JComboBox D_yy;
    private javax.swing.JComboBox M_mm;
    private javax.swing.JComboBox M_yy;
    private javax.swing.JComboBox Y_yy;
    private javax.swing.JTable at;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel per_lb;
    private javax.swing.JLabel pr_ab;
    private javax.swing.JTextField search_tf;
    private javax.swing.JComboBox searchby_cb;
    private javax.swing.JTable showrecords_tb;
    private javax.swing.JLabel sname_tf1;
    private javax.swing.JComboBox sub;
    private javax.swing.JLabel tot_lb;
    // End of variables declaration//GEN-END:variables
}
