/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class forget extends javax.swing.JFrame {

    /**
     * Creates new form forget
     */
    public forget() {
        initComponents();
        male_rb.setSelected(true);
        student_rb.setSelected(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        close_lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fname_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        male_rb = new javax.swing.JRadioButton();
        female_rb = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        dob_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        recpass = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin_rb = new javax.swing.JRadioButton();
        teacher_rb = new javax.swing.JRadioButton();
        student_rb = new javax.swing.JRadioButton();
        back_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 118, 211));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grlogo.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 200, 200));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("<html>Everything you don't know is Something you can learn.!</html>");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 270, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 10));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 240, 10));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 240, 10));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 20, 220));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 10));

        close_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px_1.png"))); // NOI18N
        close_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lbMouseClicked(evt);
            }
        });
        jPanel2.add(close_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 30, 30));

        jLabel1.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, -1));

        fname_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        fname_tf.setForeground(new java.awt.Color(60, 60, 60));
        fname_tf.setBorder(null);
        fname_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fname_tfMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fname_tfMouseEntered(evt);
            }
        });
        fname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fname_tfFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                fname_tfFocusGained(evt);
            }
        });
        jPanel2.add(fname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 240, 40));

        jLabel6.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 150, -1));

        lname_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        lname_tf.setForeground(new java.awt.Color(60, 60, 60));
        lname_tf.setBorder(null);
        lname_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lname_tfMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lname_tfMouseEntered(evt);
            }
        });
        lname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lname_tfFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                lname_tfFocusGained(evt);
            }
        });
        jPanel2.add(lname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 240, 40));

        jLabel2.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Gender");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, -1));

        male_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male_rb);
        male_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        male_rb.setText("Male");
        jPanel2.add(male_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, -1));

        female_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(female_rb);
        female_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        female_rb.setText("Female");
        jPanel2.add(female_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 110, -1));

        jLabel3.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Date of Birth");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 150, -1));

        dob_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        dob_tf.setForeground(new java.awt.Color(60, 60, 60));
        dob_tf.setBorder(null);
        dob_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dob_tfMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dob_tfMouseEntered(evt);
            }
        });
        dob_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dob_tfFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                dob_tfFocusGained(evt);
            }
        });
        jPanel2.add(dob_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 240, 40));

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Username");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        username_tf.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        username_tf.setForeground(new java.awt.Color(60, 60, 60));
        username_tf.setBorder(null);
        username_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                username_tfMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                username_tfMouseEntered(evt);
            }
        });
        username_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                username_tfFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_tfFocusGained(evt);
            }
        });
        jPanel2.add(username_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 240, 40));

        recpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reco1 copy.jpg"))); // NOI18N
        recpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recpassMouseClicked(evt);
            }
        });
        jPanel2.add(recpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 150, 40));

        jLabel4.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Select User Type");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 150, 30));

        admin_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(admin_rb);
        admin_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        admin_rb.setText("Admin");
        jPanel2.add(admin_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 100, 40));

        teacher_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(teacher_rb);
        teacher_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        teacher_rb.setText("Teacher");
        jPanel2.add(teacher_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 100, 40));

        student_rb.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(student_rb);
        student_rb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        student_rb.setText("Student");
        jPanel2.add(student_rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 90, 40));

        back_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_arrow_30px_1.png"))); // NOI18N
        back_lb.setToolTipText("Go Back to Login");
        back_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_lbMouseClicked(evt);
            }
        });
        jPanel2.add(back_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 720, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lbMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_close_lbMouseClicked

    private void fname_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fname_tfMouseEntered

    }//GEN-LAST:event_fname_tfMouseEntered

    private void fname_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fname_tfMouseExited

    }//GEN-LAST:event_fname_tfMouseExited

    private void fname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_tfFocusGained

    }//GEN-LAST:event_fname_tfFocusGained

    private void fname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fname_tfFocusLost

    }//GEN-LAST:event_fname_tfFocusLost

    private void lname_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lname_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfMouseExited

    private void lname_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lname_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfMouseEntered

    private void lname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfFocusGained

    private void lname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lname_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lname_tfFocusLost

    private void dob_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfMouseEntered

    private void dob_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dob_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfMouseExited

    private void dob_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfFocusGained

    private void dob_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dob_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_dob_tfFocusLost

    private void username_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfMouseExited

    private void username_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_username_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfMouseEntered

    private void username_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfFocusGained

    private void username_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_username_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_username_tfFocusLost

    private void recpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recpassMouseClicked
String fname="",lname="",user="",dob="",gender="",utype="";
fname=fname_tf.getText().toLowerCase();
lname=lname_tf.getText().toLowerCase();
user=username_tf.getText().toLowerCase();
dob=dob_tf.getText();
if(male_rb.isSelected()) gender="M";
if(female_rb.isSelected()) gender="F";
if(admin_rb.isSelected())
    utype="Admin";
else if(teacher_rb.isSelected())
    utype="Teacher";
else
    utype="Student";
//Fiels value Validation
if(fname.equals("")){
    JOptionPane.showMessageDialog(null, "Enter First Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
if(lname.equals("")){
    JOptionPane.showMessageDialog(null, "Enter last Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
if(user.equals("")){
    JOptionPane.showMessageDialog(null, "Enter Username Name.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}
if(dob.equals("")){
    JOptionPane.showMessageDialog(null, "Enter Date of Birth.!!","Enter full Details",JOptionPane.INFORMATION_MESSAGE);return;}

//get password
PublicFunctions pf =new PublicFunctions();
pf.Query="Select lower(fname),lower(lname),dob,gender,mobile,pass,UserType from register where username = '"+user+"';";
pf.getrec();
try
{
    pf.r.next();
    if( fname.equals(pf.r.getString(1)) && lname.equals(pf.r.getString(2)) && dob.equals(pf.r.getString(3).replace("-", "")) && gender.equals(pf.r.getString(4)) && utype.equals(pf.r.getString(7)))
    {
            long num= Long.parseLong(JOptionPane.showInputDialog("Enter Your Mobile Number..!"));
                
            if( num==Long.parseLong(pf.r.getString(5)) ){
                JOptionPane.showMessageDialog(null, "Your Password is : \n\n"+pf.r.getString("pass"),"PASSWORD",JOptionPane.INFORMATION_MESSAGE);
                new login().setVisible(true);
                this.setVisible(false);
            }
            else
                JOptionPane.showMessageDialog(null, "You Entered an Incorrect Number..!!!","ERROR",JOptionPane.ERROR_MESSAGE);
    }
    else
        JOptionPane.showMessageDialog(null, "Enter Correct Details..!!!","ERROR",JOptionPane.ERROR_MESSAGE);
}
catch(Exception e)
{
    int val=JOptionPane.showConfirmDialog(null, "User "+ user +" not Registered Yet..!\n\nIf you want to register yourself\nClick OK.!!","User not Exist",JOptionPane.YES_NO_OPTION);
    if(val==0)
    {
        new Register().setVisible(true);
        this.setVisible(false);
    }
}
    }//GEN-LAST:event_recpassMouseClicked

    private void back_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_lbMouseClicked
new login().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_back_lbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin_rb;
    private javax.swing.JLabel back_lb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel close_lb;
    private javax.swing.JTextField dob_tf;
    private javax.swing.JRadioButton female_rb;
    private javax.swing.JTextField fname_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField lname_tf;
    private javax.swing.JRadioButton male_rb;
    private javax.swing.JLabel recpass;
    private javax.swing.JRadioButton student_rb;
    private javax.swing.JRadioButton teacher_rb;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
