/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaurav
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form insert
     */
    public insert() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    String subcode,subname,Query;
    int yearsem;
    insert(String cname,int cyear,String name,String ttype, String scode)
    {
        initComponents();
        subcode=scode;
        subname=name;
        yearsem=cyear;
        this.setLocationRelativeTo(null);
        showrec_tb.setEnabled(false);
        jCheckBox1.setEnabled(false);
        confirm_bt.setEnabled(false);
        PublicFunctions pf =new PublicFunctions();
        subname_tf.setText  ("<HTML>"+subname+" ("+subcode+")</HTML>");
        testtype_tf.setText(""+ttype);
        try{
            pf.Query="Select admno,name from student where course ='"+cname+"' && year_sem="+cyear +" && status ='Persuing'";
            pf.getrec();
            DefaultTableModel model=(DefaultTableModel) showrec_tb.getModel();
            while(pf.r.next())
            {
                int admno =Integer.parseInt(pf.r.getString(1));
                String student_name =pf.r.getString(2);
                model.addRow(new Object[] {admno,student_name} );
            }
        }catch(Exception e){}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        close_lb = new javax.swing.JLabel();
        logout_lb1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showrec_tb = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        confirm_bt = new javax.swing.JButton();
        setstatus_lb = new javax.swing.JLabel();
        test_lb1 = new javax.swing.JLabel();
        totalmarks_tf = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        papertype_tf = new javax.swing.JLabel();
        subject_tf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        subname_tf = new javax.swing.JLabel();
        testtype_tf = new javax.swing.JLabel();
        papertype_tf1 = new javax.swing.JLabel();
        pid_lb = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        close_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px_1.png"))); // NOI18N
        close_lb.setToolTipText("Close");
        close_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lbMouseClicked(evt);
            }
        });

        logout_lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout_lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_to_30px.png"))); // NOI18N
        logout_lb1.setToolTipText("Back");
        logout_lb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_lb1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 784, Short.MAX_VALUE)
                .addComponent(logout_lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout_lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 870, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showrec_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adm no", "Name of Students", "Enter Obtain Marks", "Total Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showrec_tb.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(showrec_tb);
        showrec_tb.getColumnModel().getColumn(1).setResizable(false);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 850, 270));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 90, 10));

        confirm_bt.setBackground(new java.awt.Color(255, 255, 255));
        confirm_bt.setFont(new java.awt.Font("AR CENA", 1, 25)); // NOI18N
        confirm_bt.setForeground(new java.awt.Color(25, 118, 211));
        confirm_bt.setText("Confirm");
        confirm_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_btActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 110, 40));

        setstatus_lb.setBackground(new java.awt.Color(255, 255, 255));
        setstatus_lb.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        setstatus_lb.setForeground(new java.awt.Color(25, 118, 211));
        setstatus_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        setstatus_lb.setText("  ");
        jPanel1.add(setstatus_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 530, -1));

        test_lb1.setBackground(new java.awt.Color(255, 255, 255));
        test_lb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test_lb1.setForeground(new java.awt.Color(25, 118, 211));
        test_lb1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        test_lb1.setText("Total Marks : ");
        jPanel1.add(test_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        totalmarks_tf.setFont(new java.awt.Font("Aharoni", 0, 20)); // NOI18N
        totalmarks_tf.setBorder(null);
        jPanel1.add(totalmarks_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, 90, 30));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(25, 118, 211));
        jCheckBox1.setText("Do you Want Upload the current Displayed Data..!!");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 510, -1));

        papertype_tf.setBackground(new java.awt.Color(255, 255, 255));
        papertype_tf.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        papertype_tf.setForeground(new java.awt.Color(25, 118, 211));
        papertype_tf.setText("Exam Type  : ");
        jPanel1.add(papertype_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        subject_tf.setBackground(new java.awt.Color(255, 255, 255));
        subject_tf.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        subject_tf.setForeground(new java.awt.Color(25, 118, 211));
        subject_tf.setText("   Subject    : ");
        jPanel1.add(subject_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checked_30px.png"))); // NOI18N
        jLabel1.setToolTipText("Confirm");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 40, 30));

        subname_tf.setBackground(new java.awt.Color(255, 255, 255));
        subname_tf.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        subname_tf.setForeground(new java.awt.Color(25, 118, 211));
        jPanel1.add(subname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 490, 20));

        testtype_tf.setBackground(new java.awt.Color(255, 255, 255));
        testtype_tf.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        testtype_tf.setForeground(new java.awt.Color(25, 118, 211));
        testtype_tf.setText("Class Test");
        jPanel1.add(testtype_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, 20));

        papertype_tf1.setBackground(new java.awt.Color(255, 255, 255));
        papertype_tf1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        papertype_tf1.setForeground(new java.awt.Color(25, 118, 211));
        papertype_tf1.setText("Paper Id : ");
        jPanel1.add(papertype_tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, -1));

        pid_lb.setBackground(new java.awt.Color(255, 255, 255));
        pid_lb.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        pid_lb.setForeground(new java.awt.Color(25, 118, 211));
        pid_lb.setText("Paper Id : ");
        jPanel1.add(pid_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 90, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 870, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Note : - If a Student is absent in exam leave the obtain field Empty..!!!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 870, 460));

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grlogo.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 200));

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("<html>if you are not willing to learn, no one can help you. if you are determined to learn , no one can stop you </html>");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lbMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_close_lbMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
int tot_row=showrec_tb.getRowCount();
int tot=Integer.parseInt(totalmarks_tf.getText());
String obtain[]=new String[tot_row];
if(jCheckBox1.isSelected()){
    for(int i=0;i<showrec_tb.getRowCount();i++)
    {
        if(showrec_tb.getValueAt(i,2)==null)
            obtain[i]="NULL";
        else{
            if( Float.parseFloat(showrec_tb.getValueAt(i,2).toString()) > tot ){
                JOptionPane.showMessageDialog(this, "Marks of : "+showrec_tb.getValueAt(i, 1)+" is greater than total marks..!"); return;}
            obtain[i]=showrec_tb.getValueAt(i, 2).toString();
        }
    }
Query="insert into marks values";
for(int i=0;i<tot_row;i++){
    int admno=Integer.parseInt(showrec_tb.getValueAt(i, 0).toString());
    String test_type=testtype_tf.getText();
    Query=Query+"("+admno+", '"+test_type+"', '"+subname+"', '"+obtain[i]+"', "+tot+", '"+pid_lb.getText()+"',date(Now()),'"+subcode+"',"+yearsem+")";
    if(i<tot_row-1)
        Query=Query+",\n";
}
    confirm_bt.setEnabled(true);
}
else
    confirm_bt.setEnabled(false);
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
  
    }//GEN-LAST:event_formWindowIconified

    private void confirm_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_btActionPerformed
PublicFunctions pf=new PublicFunctions();
try{
    pf.Query=Query;
    pf.updtrec();
    JOptionPane.showMessageDialog(this, "Marks of all Students Records Sucessfully..!!!");
    new TeacherMenu().setVisible(true);
    this.setVisible(false);
}catch(Exception e){
    JOptionPane.showMessageDialog(this, "Error while Recording marks data..!!!"); return;
}

    }//GEN-LAST:event_confirm_btActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
if(totalmarks_tf.getText().equals(""))
{
    JOptionPane.showMessageDialog(this, "First Enter Total Mark..!");
}
else
{
    int req=JOptionPane.showConfirmDialog(this,"Please confirm Total marks once more...\n You can not change later..! ","Confirm", JOptionPane.YES_NO_OPTION);
    if(req==0){
        try{
            int tot=Integer.parseInt(totalmarks_tf.getText());
            for(int i=0;i<showrec_tb.getRowCount();i++)
                showrec_tb.setValueAt(tot, i, 3);
            showrec_tb.setEnabled(true);
            jCheckBox1.setEnabled(true);
            totalmarks_tf.setEditable(false);
            jLabel1.setEnabled(false);
        }catch(Exception e){JOptionPane.showMessageDialog(this, "Please Enter an Integer Value..!!");}    
    }
}
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
if(showrec_tb.getRowCount()==0)
{
    JOptionPane.showMessageDialog(this, "No Record Found..!!!");
    this.setVisible(false);
    new TeacherMenu().setVisible(true);
}   
PublicFunctions pf=new PublicFunctions();
int id=0;
try{
    pf.Query="Select Substring(testid,2) from marks;";
    pf.getrec();
    while(pf.r.next())
    {
        if(pf.r.getInt(1)>id)
            id=pf.r.getInt(1);
    }
    id+=1;
    pid_lb.setText("p"+id);
}catch(Exception e){   JOptionPane.showMessageDialog(null, "Something Wrong..!!!","ERROR",JOptionPane.ERROR_MESSAGE); return;  }
    }//GEN-LAST:event_formWindowActivated

    private void logout_lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lb1MouseClicked
        new TeacherMenu().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_logout_lb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_lb;
    private javax.swing.JButton confirm_bt;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logout_lb1;
    private javax.swing.JLabel papertype_tf;
    private javax.swing.JLabel papertype_tf1;
    private javax.swing.JLabel pid_lb;
    private javax.swing.JLabel setstatus_lb;
    private javax.swing.JTable showrec_tb;
    private javax.swing.JLabel subject_tf;
    private javax.swing.JLabel subname_tf;
    private javax.swing.JLabel test_lb1;
    private javax.swing.JLabel testtype_tf;
    private javax.swing.JTextField totalmarks_tf;
    // End of variables declaration//GEN-END:variables
}
