/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class selectsubject extends javax.swing.JFrame {

    /**
     * Creates new form selectsubject
     */
    public selectsubject() {
        initComponents();
        
    }
    String cname;
    int cyear,i;
    String[] scode;
    String cf_action;
    public selectsubject(String course_name, int yearsem,String action) {
        initComponents();
        cf_action=action;
        this.setLocationRelativeTo(null);   
        cname=course_name;
        cyear=yearsem;
        PublicFunctions pf =new PublicFunctions();
        try{
            pf.Query="select sname,scode from course c,course_details c1, subjects s where c.cid=c1.cid && s.ccys=c1.ccys && cname='"+cname+"' && year_sem="+cyear+" ";
            pf.getrec();
            pf.r.last();
            scode=new String[pf.r.getRow()];
            pf.r.beforeFirst();
            subject_cb.removeAllItems();
            i=0;
            while(pf.r.next()){
                subject_cb.addItem(pf.r.getString(1));
                scode[i++]=pf.r.getString(2);
            }
            scode_tf.setText(scode[0]);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Subjects are not added to this course..!!");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Subject_lb = new javax.swing.JLabel();
        test_lb = new javax.swing.JLabel();
        subject_cb = new javax.swing.JComboBox();
        test_cb = new javax.swing.JComboBox();
        next_lb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scode_tf = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logout_lb1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Subject_lb.setBackground(new java.awt.Color(255, 255, 255));
        Subject_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        Subject_lb.setForeground(new java.awt.Color(25, 118, 211));
        Subject_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Subject_lb.setText("Select Subject");
        jPanel1.add(Subject_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 350, 40));

        test_lb.setBackground(new java.awt.Color(255, 255, 255));
        test_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        test_lb.setForeground(new java.awt.Color(25, 118, 211));
        test_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        test_lb.setText("Select Test Type");
        jPanel1.add(test_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 350, 40));

        subject_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                subject_cbItemStateChanged(evt);
            }
        });
        jPanel1.add(subject_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 30));

        test_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class Test", "Internal", "Model", "Final" }));
        test_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                test_cbItemStateChanged(evt);
            }
        });
        jPanel1.add(test_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 210, 30));

        next_lb.setBackground(new java.awt.Color(255, 255, 255));
        next_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        next_lb.setForeground(new java.awt.Color(25, 118, 211));
        next_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_next_page_60px.png"))); // NOI18N
        next_lb.setToolTipText("Next");
        next_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                next_lbMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_lbMouseClicked(evt);
            }
        });
        jPanel1.add(next_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Sub Code : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        scode_tf.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        scode_tf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        scode_tf.setText("  ");
        jPanel1.add(scode_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 350, 340));

        jPanel5.setBackground(new java.awt.Color(25, 118, 211));
        jPanel5.setToolTipText("");
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout_lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_to_30px_1.png"))); // NOI18N
        logout_lb1.setToolTipText("Back");
        logout_lb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_lb1MouseClicked(evt);
            }
        });
        jPanel5.add(logout_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grlogo.png"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 200));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>“Aim for the moon. If you miss, you may hit a star.”<br><br>—W. Clement Stone</html>");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 230, 130));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 380));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        close_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px_1.png"))); // NOI18N
        close_lb.setToolTipText("Close");
        close_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 309, Short.MAX_VALUE)
                .addComponent(close_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 350, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subject_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_subject_cbItemStateChanged
scode_tf.setText(scode[subject_cb.getSelectedIndex()]);
    }//GEN-LAST:event_subject_cbItemStateChanged

    private void test_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_test_cbItemStateChanged

    }//GEN-LAST:event_test_cbItemStateChanged

    private void next_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_lbMouseClicked
String subname=subject_cb.getSelectedItem().toString();
String ttype=test_cb.getSelectedItem().toString();
if(cf_action.equals("add"))
   new insert(cname,cyear,subname,ttype,scode_tf.getText()).setVisible(true);
if(cf_action.equals("update"))
   new updatemarks(scode_tf.getText()).setVisible(true);
if(cf_action.equals("delete"))
    new deleter_paper(scode_tf.getText()).setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_next_lbMouseClicked

    private void logout_lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lb1MouseClicked
        new menu().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_logout_lb1MouseClicked

    private void close_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lbMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_lbMouseClicked

    private void next_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_lbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_next_lbMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selectsubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selectsubject().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Subject_lb;
    private javax.swing.JLabel close_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logout_lb1;
    private javax.swing.JLabel next_lb;
    private javax.swing.JLabel scode_tf;
    private javax.swing.JComboBox subject_cb;
    private javax.swing.JComboBox test_cb;
    private javax.swing.JLabel test_lb;
    // End of variables declaration//GEN-END:variables
}
