/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class select_course_yearsem extends javax.swing.JFrame {

    /**
     * Creates new form select_course_yearsem
     */
    public select_course_yearsem() {
        initComponents();
    }
    int tot=0,i=0;
    int[] max_yearsem;
    String[] course_type;
    String cf_action;
    public select_course_yearsem(String action) {
        initComponents();
        cf_action=action;
        this.setLocationRelativeTo(null);
        PublicFunctions pf =new PublicFunctions();
        try{
            pf.Query="select count(*) from course";
            pf.getrec();
            pf.r.next();
            tot=Integer.parseInt(pf.r.getString(1));    //get total no of courses
            max_yearsem=new int[tot];
            course_type=new String[tot];
            pf.Query="select c.cname, max(c1.year_sem),ctype from course c,course_details c1 where c.cid=c1.cid group by cname";
            pf.getrec(); 
            while(pf.r.next())
            {
                course_cb.addItem(pf.r.getString(1));
                max_yearsem[i]=Integer.parseInt(pf.r.getString(2));
                course_type[i]=pf.r.getString(3);
                i++;
                if(max_yearsem[0]>=i)   yearsem_cb.addItem(i);
            }
            year_lb.setText("Select "+course_type[0]);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        close_lb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        course_lb = new javax.swing.JLabel();
        course_cb = new javax.swing.JComboBox();
        yearsem_cb = new javax.swing.JComboBox();
        next_lb = new javax.swing.JLabel();
        year_lb = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        logout_lb1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        close_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px_1.png"))); // NOI18N
        close_lb.setToolTipText("Close");
        close_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 309, Short.MAX_VALUE)
                .addComponent(close_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 350, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        course_lb.setBackground(new java.awt.Color(255, 255, 255));
        course_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        course_lb.setForeground(new java.awt.Color(25, 118, 211));
        course_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        course_lb.setText("Select Course");
        jPanel1.add(course_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

        course_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                course_cbItemStateChanged(evt);
            }
        });
        jPanel1.add(course_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 210, 30));

        yearsem_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearsem_cbItemStateChanged(evt);
            }
        });
        yearsem_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsem_cbActionPerformed(evt);
            }
        });
        yearsem_cb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                yearsem_cbInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel1.add(yearsem_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 210, 30));

        next_lb.setBackground(new java.awt.Color(255, 255, 255));
        next_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        next_lb.setForeground(new java.awt.Color(25, 118, 211));
        next_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_next_page_60px.png"))); // NOI18N
        next_lb.setToolTipText("Next");
        next_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_lbMouseClicked(evt);
            }
        });
        jPanel1.add(next_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        year_lb.setBackground(new java.awt.Color(255, 255, 255));
        year_lb.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        year_lb.setForeground(new java.awt.Color(25, 118, 211));
        year_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        year_lb.setText("Select");
        jPanel1.add(year_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 350, 340));

        jPanel5.setBackground(new java.awt.Color(25, 118, 211));
        jPanel5.setToolTipText("");
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout_lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_to_30px_1.png"))); // NOI18N
        logout_lb1.setToolTipText("Back");
        logout_lb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_lb1MouseClicked(evt);
            }
        });
        jPanel5.add(logout_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grlogo.png"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 200));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>A child without education is like a bird without wings.</html>");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 100));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lbMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_lbMouseClicked

    private void course_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_course_cbItemStateChanged
        int seleted_course=course_cb.getSelectedIndex();
        yearsem_cb.removeAllItems();
        year_lb.setText("Select "+course_type[seleted_course]);
        for(int i=1;i<=max_yearsem[seleted_course];i++)
        {
            yearsem_cb.addItem(i);
        }
    }//GEN-LAST:event_course_cbItemStateChanged

    private void yearsem_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearsem_cbItemStateChanged

    }//GEN-LAST:event_yearsem_cbItemStateChanged

    private void yearsem_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsem_cbActionPerformed

    }//GEN-LAST:event_yearsem_cbActionPerformed

    private void yearsem_cbInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_yearsem_cbInputMethodTextChanged

    }//GEN-LAST:event_yearsem_cbInputMethodTextChanged

    private void next_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_lbMouseClicked
String course_name=course_cb.getSelectedItem().toString();
int yearsem=Integer.parseInt(yearsem_cb.getSelectedItem().toString());
new selectsubject(course_name, yearsem,cf_action).setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_next_lbMouseClicked

    private void logout_lb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lb1MouseClicked
new TeacherMenu().setVisible(true);
this.setVisible(false);      
    }//GEN-LAST:event_logout_lb1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(select_course_yearsem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new select_course_yearsem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_lb;
    private javax.swing.JComboBox course_cb;
    private javax.swing.JLabel course_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logout_lb1;
    private javax.swing.JLabel next_lb;
    private javax.swing.JLabel year_lb;
    private javax.swing.JComboBox yearsem_cb;
    // End of variables declaration//GEN-END:variables
}
