/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaurav
 */
public class updatemarks extends javax.swing.JFrame {

    /**
     * Creates new form updatemarks
     */
    public updatemarks() {
        initComponents();
    }
    String code,Query;
    public updatemarks(String scode) {
        initComponents();
        totalmarks_tf.setEditable(false);
        conf_lb.setEnabled(false);
        showrec_tb.setEnabled(false);
        jCheckBox1.setEnabled(false);
        update_bt.setEnabled(false);
        code=scode;
        PublicFunctions pf=new PublicFunctions();
        try
        {
            pf.Query="Select Distinct(testid) from marks where scode='"+scode+"'";
            pf.getrec();
            while(pf.r.next())
            {
                testid_cb.addItem(pf.r.getString(1));
            }
            pf.Query="Select sname from subjects where scode='"+code+"'";
            pf.getrec();
            pf.r.next();
            subname_lb.setText(pf.r.getString(1));         
        }
        catch(Exception e)        {           
        }
        if(testid_cb.getItemCount()<1)
        {
            JOptionPane.showMessageDialog(this, "No Record Found..!!!");
            new TeacherMenu().setVisible(true);
            this.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close_lb = new javax.swing.JLabel();
        logout_lb = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        testid_cb = new javax.swing.JComboBox();
        year_lb = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showrec_tb = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        update_bt = new javax.swing.JButton();
        test_lb1 = new javax.swing.JLabel();
        totalmarks_tf = new javax.swing.JTextField();
        conf_lb = new javax.swing.JLabel();
        year_lb1 = new javax.swing.JLabel();
        subname_lb = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(25, 118, 211));
        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grlogo.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 200));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>if you are not willing to learn, no one can help you. if you are determined to learn , no one can stop you</html>");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 230, 130));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 490));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        close_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px_1.png"))); // NOI18N
        close_lb.setToolTipText("Close");
        close_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lbMouseClicked(evt);
            }
        });

        logout_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_to_30px.png"))); // NOI18N
        logout_lb.setToolTipText("Log Out");
        logout_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_lbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 542, Short.MAX_VALUE)
                .addComponent(logout_lb)
                .addGap(16, 16, 16)
                .addComponent(close_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logout_lb, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(close_lb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 630, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        testid_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                testid_cbItemStateChanged(evt);
            }
        });
        testid_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testid_cbActionPerformed(evt);
            }
        });
        testid_cb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                testid_cbInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel1.add(testid_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 160, 30));

        year_lb.setBackground(new java.awt.Color(255, 255, 255));
        year_lb.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        year_lb.setForeground(new java.awt.Color(25, 118, 211));
        year_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        year_lb.setText("Select Test");
        jPanel1.add(year_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 120, 30));

        showrec_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adm no", "Name of Students", "Enter Obtain Marks", "Total Marks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showrec_tb.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(showrec_tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 610, 270));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 80, 10));

        jButton1.setBackground(new java.awt.Color(25, 118, 211));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 160, 30));

        update_bt.setBackground(new java.awt.Color(25, 118, 211));
        update_bt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        update_bt.setForeground(new java.awt.Color(255, 255, 255));
        update_bt.setText("UPDATE");
        update_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btActionPerformed(evt);
            }
        });
        jPanel1.add(update_bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 120, 30));

        test_lb1.setBackground(new java.awt.Color(255, 255, 255));
        test_lb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        test_lb1.setForeground(new java.awt.Color(25, 118, 211));
        test_lb1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        test_lb1.setText("Total Marks : ");
        jPanel1.add(test_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        totalmarks_tf.setEditable(false);
        totalmarks_tf.setBackground(new java.awt.Color(255, 255, 255));
        totalmarks_tf.setFont(new java.awt.Font("Aharoni", 0, 20)); // NOI18N
        totalmarks_tf.setBorder(null);
        jPanel1.add(totalmarks_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 80, 30));

        conf_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        conf_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_checked_30px.png"))); // NOI18N
        conf_lb.setToolTipText("Confirm");
        conf_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        conf_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conf_lbMouseClicked(evt);
            }
        });
        jPanel1.add(conf_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 40, 30));

        year_lb1.setBackground(new java.awt.Color(255, 255, 255));
        year_lb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        year_lb1.setForeground(new java.awt.Color(255, 0, 0));
        year_lb1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        year_lb1.setText("Subject : ");
        jPanel1.add(year_lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 20));

        subname_lb.setBackground(new java.awt.Color(255, 255, 255));
        subname_lb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subname_lb.setForeground(new java.awt.Color(255, 0, 0));
        subname_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(subname_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 260, 20));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(25, 118, 211));
        jCheckBox1.setText("Check the box if you want to Upload the current Displayed Data..!!");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 440, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lbMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_lbMouseClicked

    private void logout_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_lbMouseClicked

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
int tot_row=showrec_tb.getRowCount();
int tot=Integer.parseInt(totalmarks_tf.getText());
String obtain[]=new String[tot_row];
if(jCheckBox1.isSelected()){         
    for(int i=0;i<showrec_tb.getRowCount();i++)
    {
        if(showrec_tb.getValueAt(i,2)==null)
            obtain[i]="NULL";
        else{
            if( Float.parseFloat(showrec_tb.getValueAt(i,2).toString()) > tot ){
                JOptionPane.showMessageDialog(this, "Marks of : "+showrec_tb.getValueAt(i, 1)+" is greater than total marks..!"); return;}
            obtain[i]=showrec_tb.getValueAt(i, 2).toString();
        }
    }            
    update_bt.setEnabled(true);
    showrec_tb.setEnabled(false);
}
else{
    showrec_tb.setEnabled(true);
    update_bt.setEnabled(false);
}
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void conf_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conf_lbMouseClicked
        if(conf_lb.isEnabled())
        {
            conf_lb.setEnabled(false);
            totalmarks_tf.setEditable(false);
            if(totalmarks_tf.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "First Enter Total Mark..!");
            }
            else
            {
                int req=JOptionPane.showConfirmDialog(this,"Please confirm Total marks once more...\n You can not change later..! ","COnfirm",JOptionPane.YES_NO_OPTION);
                if(req==0){
                    try{
                        int tot=Integer.parseInt(totalmarks_tf.getText());
                        for(int i=0;i<showrec_tb.getRowCount();i++)
                            showrec_tb.setValueAt(tot, i, 3);
                        showrec_tb.setEnabled(true);
                        jCheckBox1.setEnabled(true);
                    }catch(Exception e){JOptionPane.showMessageDialog(this, "Please Enter an Integer Value..!!");}
                }
            }
        }
    }//GEN-LAST:event_conf_lbMouseClicked

    private void update_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btActionPerformed
int tot_row=showrec_tb.getRowCount();
int tot=Integer.parseInt(totalmarks_tf.getText());
String obtain[]=new String[tot_row];
for(int i=0;i<showrec_tb.getRowCount();i++)
{
    if(showrec_tb.getValueAt(i,2)==null)
        obtain[i]="NULL";
    else{
        if( Float.parseFloat(showrec_tb.getValueAt(i,2).toString()) > tot ){
            JOptionPane.showMessageDialog(this, "Marks of : "+showrec_tb.getValueAt(i, 1)+" is greater than total marks..!"); return;}
        obtain[i]=showrec_tb.getValueAt(i, 2).toString();
    }
}         
PublicFunctions pf=new PublicFunctions();
for(int i=0;i<showrec_tb.getRowCount();i++)
{
    try{
        pf.Query="update marks set obtain='"+obtain[i]+"', total='"+tot+"' where admno="+showrec_tb.getValueAt(i, 0).toString()+" && testid='"+testid_cb.getSelectedItem().toString()+"'";
        pf.updtrec();
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"Error While updating marks records..!!!"); return;
    }
}
JOptionPane.showMessageDialog(this, "Records Update sucessfully..!!!");
new TeacherMenu().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_update_btActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PublicFunctions pf =new PublicFunctions();
        pf.emptyTable(showrec_tb);
        try
        {
            DefaultTableModel model=(DefaultTableModel) showrec_tb.getModel();
            pf.Query="Select m.admno,s.name,obtain,total from marks m, student s where scode='"+code+"' and testid='"+testid_cb.getSelectedItem().toString()+"' and m.admno=s.admno";
            pf.getrec();
            int i=0;
            while(pf.r.next())
            {
                if(pf.r.getString(3).equals("NULL")){
                    model.addRow(new Object[] {pf.r.getString(1),pf.r.getString(2)});
                    showrec_tb.setValueAt(pf.r.getString(4), i, 3);
                }
                else{
                    model.addRow(new Object[] {pf.r.getString(1),pf.r.getString(2),pf.r.getFloat(3),pf.r.getString(4)});
                }
                i++;
            }
            totalmarks_tf.setEditable(true);
            conf_lb.setEnabled(true);
        }catch(Exception e){
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void testid_cbInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_testid_cbInputMethodTextChanged

    }//GEN-LAST:event_testid_cbInputMethodTextChanged

    private void testid_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testid_cbActionPerformed

    }//GEN-LAST:event_testid_cbActionPerformed

    private void testid_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_testid_cbItemStateChanged

    }//GEN-LAST:event_testid_cbItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatemarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatemarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatemarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatemarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updatemarks().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel close_lb;
    private javax.swing.JLabel conf_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout_lb;
    private javax.swing.JTable showrec_tb;
    private javax.swing.JLabel subname_lb;
    private javax.swing.JLabel test_lb1;
    private javax.swing.JComboBox testid_cb;
    private javax.swing.JTextField totalmarks_tf;
    private javax.swing.JButton update_bt;
    private javax.swing.JLabel year_lb;
    private javax.swing.JLabel year_lb1;
    // End of variables declaration//GEN-END:variables
}
