/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gaurav
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(2, false);
        showrecords_tb.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);        
    }
    void emptyTable( javax.swing.JTable tb_name)
    {
        DefaultTableModel model= (DefaultTableModel) tb_name.getModel();
        int row=tb_name.getRowCount()-1;
        while(row>=0)
            model.removeRow(row--);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        logout_lb3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close_lb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        searchby_cb = new javax.swing.JComboBox();
        jSeparator9 = new javax.swing.JSeparator();
        search_tf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showrecords_tb = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sname_tf = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stream_tf = new javax.swing.JLabel();
        yearsem_lb = new javax.swing.JLabel();
        yearsem_cb = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        subject_cb = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        ttype_cb = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        sname_tf1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paper_tb = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tot_lb = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        attend_lb = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        per_lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(25, 118, 211));
        jPanel7.setToolTipText("");
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout_lb3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout_lb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_to_30px_1.png"))); // NOI18N
        logout_lb3.setToolTipText("Back");
        logout_lb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout_lb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_lb3MouseClicked(evt);
            }
        });
        jPanel7.add(logout_lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grlogo.png"))); // NOI18N
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 200, 200));

        jLabel1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html>Failure doesn't mean the GAME OVER, IT means try again with EXPERIENCE</html>");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 230, 130));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 540));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_30px_1.png"))); // NOI18N
        close_lb.setToolTipText("Close");
        close_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_lbMouseClicked(evt);
            }
        });
        jPanel2.add(close_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 40, 44));

        jLabel8.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Search By : ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        searchby_cb.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        searchby_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admno", "Name" }));
        jPanel2.add(searchby_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 150, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, 10));

        search_tf.setFont(new java.awt.Font("Aparajita", 1, 18)); // NOI18N
        search_tf.setForeground(new java.awt.Color(25, 118, 211));
        search_tf.setBorder(null);
        search_tf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                search_tfMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                search_tfMouseExited(evt);
            }
        });
        search_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                search_tfFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                search_tfFocusGained(evt);
            }
        });
        search_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_tfKeyReleased(evt);
            }
        });
        jPanel2.add(search_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 230, 40));

        jButton1.setBackground(new java.awt.Color(25, 118, 211));
        jButton1.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_30px.png"))); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 140, 70));

        jTabbedPane1.setForeground(new java.awt.Color(25, 118, 211));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        showrecords_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Adm no", "Full Name", "Gender", "DOB", "Course", "Year/Sem", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        showrecords_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showrecords_tbMouseClicked(evt);
            }
        });
        showrecords_tb.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                showrecords_tbCaretPositionChanged(evt);
            }
        });
        showrecords_tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                showrecords_tbKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(showrecords_tb);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Show Record", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Name of Student :");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        sname_tf.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        sname_tf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sname_tf.setText("GAURAV KUMAR");
        jPanel4.add(sname_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 240, -1));

        jLabel10.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Stream : ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        stream_tf.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        stream_tf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stream_tf.setText("BCA");
        jPanel4.add(stream_tf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 250, -1));

        yearsem_lb.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        yearsem_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        yearsem_lb.setText("Year : ");
        jPanel4.add(yearsem_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, 30));

        yearsem_cb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        yearsem_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearsem_cbItemStateChanged(evt);
            }
        });
        jPanel4.add(yearsem_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 70, 30));

        jLabel12.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Subject : ");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 30));

        subject_cb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        jPanel4.add(subject_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 210, 30));

        jLabel13.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Paper Type :");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 100, 30));

        ttype_cb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        ttype_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class Test", "Internal", "Model", "Final" }));
        jPanel4.add(ttype_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, 30));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 580, 10));

        jButton2.setBackground(new java.awt.Color(25, 118, 211));
        jButton2.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_show_property_50px.png"))); // NOI18N
        jButton2.setText("<html>Show<br>Report<html>");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 150, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Report", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sname_tf1.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        sname_tf1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sname_tf1.setText("  ");
        jPanel6.add(sname_tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        paper_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Paper ID", "Obtain", "Total", "Date of Exam", "Percentage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paper_tb.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(paper_tb);
        paper_tb.getColumnModel().getColumn(0).setResizable(false);
        paper_tb.getColumnModel().getColumn(1).setResizable(false);
        paper_tb.getColumnModel().getColumn(2).setResizable(false);
        paper_tb.getColumnModel().getColumn(4).setResizable(false);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 590, 250));

        jLabel11.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Total Paper Conduct : ");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 170, 20));

        tot_lb.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        tot_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel6.add(tot_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 20));

        jLabel15.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Attend Paper : ");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 20));

        attend_lb.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        attend_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel6.add(attend_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 160, 20));

        jLabel16.setFont(new java.awt.Font("Aparajita", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Percentage :");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 100, 20));

        per_lb.setFont(new java.awt.Font("Aparajita", 0, 20)); // NOI18N
        per_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel6.add(per_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 70, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Show", jPanel5);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 620, 380));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 640, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_lb3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_lb3MouseClicked
  
    }//GEN-LAST:event_logout_lb3MouseClicked

    private void close_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_lbMouseClicked
        System.exit(0);
    }//GEN-LAST:event_close_lbMouseClicked

    private void search_tfMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_tfMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfMouseEntered

    private void search_tfMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_tfMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfMouseExited

    private void search_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfFocusLost

    private void search_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search_tfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_search_tfFocusGained

    private void search_tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_tfKeyReleased

    }//GEN-LAST:event_search_tfKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(search_tf.getText().equals(""))
    return;
PublicFunctions pf=new PublicFunctions();
try{
    pf.Query="Select Admno,name,gender,dob,course,year_sem,status from Student where "+searchby_cb.getSelectedItem().toString()+" like '%"+search_tf.getText()+"%';";
    pf.getrec();
    emptyTable(showrecords_tb);
    DefaultTableModel model= (DefaultTableModel) showrecords_tb.getModel();
    while(pf.r.next())
    {
        model.addRow(new Object[] {
            pf.r.getString(1),
            pf.r.getString(2),
            pf.r.getString(3),
            pf.r.getString(4),
            pf.r.getString(5),
            pf.r.getString(6),
            pf.r.getString(7)
        } );
    }
}catch(Exception e){
    JOptionPane.showMessageDialog(this, "Erroe while setting table data into form"+e);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showrecords_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showrecords_tbMouseClicked
sname_tf.setText(showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 1).toString());
stream_tf.setText(showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 4).toString());
int max=Integer.parseInt(showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 5).toString());
yearsem_cb.removeAllItems();
int i=1;
while(i<=max)
    yearsem_cb.addItem(i++);
jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_showrecords_tbMouseClicked

    private void showrecords_tbCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_showrecords_tbCaretPositionChanged

    }//GEN-LAST:event_showrecords_tbCaretPositionChanged

    private void showrecords_tbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_showrecords_tbKeyReleased

    }//GEN-LAST:event_showrecords_tbKeyReleased

    private void yearsem_cbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearsem_cbItemStateChanged
String cname=stream_tf.getText();
if(yearsem_cb.getItemCount()<1) return;
int cyear=Integer.parseInt(yearsem_cb.getSelectedItem().toString());
PublicFunctions pf =new PublicFunctions();
try{
    pf.Query="select sname from course c,course_details c1, subjects s where c.cid=c1.cid && s.ccys=c1.ccys && cname='"+cname+"' && year_sem="+cyear+"";
    pf.getrec();
    subject_cb.removeAllItems();
    while(pf.r.next())
        subject_cb.addItem(pf.r.getString(1));
}catch(Exception e)
{}
    }//GEN-LAST:event_yearsem_cbItemStateChanged

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
PublicFunctions pf=new PublicFunctions();
int admno=Integer.parseInt(showrecords_tb.getValueAt(showrecords_tb.getSelectedRow(), 0).toString());
int year_sem=Integer.parseInt(yearsem_cb.getSelectedItem().toString());
String Sub=subject_cb.getSelectedItem().toString();
String type=ttype_cb.getSelectedItem().toString();
int attend=0;
float sum_obtain=0,tot=0;
try
{
    pf.Query="select testid,obtain,total,date_of_exam from marks where admno="+admno+" && year_sem="+year_sem+" && subject='"+Sub+"' && type='"+type+"'";
    pf.getrec();
    emptyTable(paper_tb);
    DefaultTableModel model= (DefaultTableModel) paper_tb.getModel();
    while(pf.r.next())
    {
        if(pf.r.getString(2).equals("NULL")){
            model.addRow(new Object[] {
            pf.r.getString(1),
            pf.r.getString(2),
            pf.r.getString(3),
            pf.r.getString(4)            
        } );
        }
        else{
            attend++;   
            sum_obtain=sum_obtain+pf.r.getFloat(2);
            tot=tot+pf.r.getFloat(3);
            
            model.addRow(new Object[] {
            pf.r.getString(1),
            pf.r.getString(2),
            pf.r.getString(3),
            pf.r.getString(4),
            (pf.r.getFloat(2)/pf.r.getFloat(3))*100 +" %"
        } );
        }        
    }
    jTabbedPane1.setSelectedIndex(2);
 tot_lb.setText(""+paper_tb.getRowCount());
 attend_lb.setText(""+attend);
 per_lb.setText(""+(sum_obtain/tot)*100+" % ");
}catch(Exception e)
{
    JOptionPane.showMessageDialog(this, "Something Wrong...!!!");
}

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attend_lb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel close_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout_lb3;
    private javax.swing.JTable paper_tb;
    private javax.swing.JLabel per_lb;
    private javax.swing.JTextField search_tf;
    private javax.swing.JComboBox searchby_cb;
    private javax.swing.JTable showrecords_tb;
    private javax.swing.JLabel sname_tf;
    private javax.swing.JLabel sname_tf1;
    private javax.swing.JLabel stream_tf;
    private javax.swing.JComboBox subject_cb;
    private javax.swing.JLabel tot_lb;
    private javax.swing.JComboBox ttype_cb;
    private javax.swing.JComboBox yearsem_cb;
    private javax.swing.JLabel yearsem_lb;
    // End of variables declaration//GEN-END:variables
}
