/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class don extends javax.swing.JFrame {

    /**
     * Creates new form don
     */
    int same=0;
    public don() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        user_lb = new javax.swing.JLabel();
        user_lb2 = new javax.swing.JLabel();
        user_lb4 = new javax.swing.JLabel();
        user_lb6 = new javax.swing.JLabel();
        user_lb8 = new javax.swing.JLabel();
        user_lb11 = new javax.swing.JLabel();
        fcont = new javax.swing.JTextField();
        fm = new javax.swing.JRadioButton();
        ff = new javax.swing.JRadioButton();
        fdob = new javax.swing.JTextField();
        flname = new javax.swing.JTextField();
        ffname = new javax.swing.JTextField();
        user_lb1 = new javax.swing.JLabel();
        user_lb3 = new javax.swing.JLabel();
        user_lb5 = new javax.swing.JLabel();
        user_lb7 = new javax.swing.JLabel();
        user_lb9 = new javax.swing.JLabel();
        fadd = new javax.swing.JTextField();
        fblood = new javax.swing.JComboBox();
        fweight = new javax.swing.JTextField();
        femail = new javax.swing.JTextField();
        fmname = new javax.swing.JTextField();
        forg = new javax.swing.JComboBox();
        fqty = new javax.swing.JTextField();
        user_lb10 = new javax.swing.JLabel();
        user_lb12 = new javax.swing.JLabel();
        faadhar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><U>Please Fill The following Details</html>");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        user_lb.setBackground(new java.awt.Color(255, 255, 255));
        user_lb.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb.setForeground(new java.awt.Color(0, 0, 153));
        user_lb.setText("First Name");

        user_lb2.setBackground(new java.awt.Color(255, 255, 255));
        user_lb2.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb2.setForeground(new java.awt.Color(0, 0, 153));
        user_lb2.setText("Last Name");

        user_lb4.setBackground(new java.awt.Color(255, 255, 255));
        user_lb4.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb4.setForeground(new java.awt.Color(0, 0, 153));
        user_lb4.setText("DOB");

        user_lb6.setBackground(new java.awt.Color(255, 255, 255));
        user_lb6.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb6.setForeground(new java.awt.Color(0, 0, 153));
        user_lb6.setText("Gender");

        user_lb8.setBackground(new java.awt.Color(255, 255, 255));
        user_lb8.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb8.setForeground(new java.awt.Color(0, 0, 153));
        user_lb8.setText("Contact");

        user_lb11.setBackground(new java.awt.Color(255, 255, 255));
        user_lb11.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb11.setForeground(new java.awt.Color(0, 0, 153));
        user_lb11.setText("<html>Select Organization near you<br>Where you donate Blood</html>");

        fcont.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fcont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcontActionPerformed(evt);
            }
        });

        buttonGroup1.add(fm);
        fm.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fm.setText("M");

        buttonGroup1.add(ff);
        ff.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ff.setText("F");

        fdob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdobActionPerformed(evt);
            }
        });

        flname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        flname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flnameActionPerformed(evt);
            }
        });

        ffname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ffname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffnameActionPerformed(evt);
            }
        });

        user_lb1.setBackground(new java.awt.Color(255, 255, 255));
        user_lb1.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb1.setForeground(new java.awt.Color(0, 0, 153));
        user_lb1.setText("Middle Name");

        user_lb3.setBackground(new java.awt.Color(255, 255, 255));
        user_lb3.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb3.setForeground(new java.awt.Color(0, 0, 153));
        user_lb3.setText("Email");

        user_lb5.setBackground(new java.awt.Color(255, 255, 255));
        user_lb5.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb5.setForeground(new java.awt.Color(0, 0, 153));
        user_lb5.setText("Weight");

        user_lb7.setBackground(new java.awt.Color(255, 255, 255));
        user_lb7.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb7.setForeground(new java.awt.Color(0, 0, 153));
        user_lb7.setText("Blood Group");

        user_lb9.setBackground(new java.awt.Color(255, 255, 255));
        user_lb9.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb9.setForeground(new java.awt.Color(0, 0, 153));
        user_lb9.setText("Address");

        fadd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        fblood.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fblood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A +ve", "A -ve", "B +ve", "B -ve", "O +ve", "O -ve", "AB +ve", "AB -ve" }));

        fweight.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        femail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        fmname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        forg.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        forg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sparsh Multi-Spaciality Hospital", "Sec-9 Hospital", "Vinayak Hospital", "Chandulal Hospital", "Sarkar Hospital " }));

        fqty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fqtyActionPerformed(evt);
            }
        });

        user_lb10.setBackground(new java.awt.Color(255, 255, 255));
        user_lb10.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb10.setForeground(new java.awt.Color(0, 0, 153));
        user_lb10.setText("Qty.");

        user_lb12.setBackground(new java.awt.Color(255, 255, 255));
        user_lb12.setFont(new java.awt.Font("AR ESSENCE", 0, 23)); // NOI18N
        user_lb12.setForeground(new java.awt.Color(0, 0, 153));
        user_lb12.setText("AAdhar No");

        faadhar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(user_lb11, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(forg, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(user_lb)
                                    .addGap(18, 18, 18)
                                    .addComponent(ffname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(user_lb1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(user_lb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(user_lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(user_lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(fdob, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(user_lb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(flname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(user_lb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(fm)
                                                    .addGap(45, 45, 45)
                                                    .addComponent(ff))
                                                .addComponent(fcont, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(user_lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(user_lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(user_lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(user_lb10, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(fqty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(user_lb12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(femail, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fmname, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fweight, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(fblood, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fadd, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(faadhar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb)
                    .addComponent(ffname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_lb1)
                    .addComponent(fmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb2)
                    .addComponent(flname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_lb3)
                    .addComponent(femail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb4)
                    .addComponent(fdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_lb5)
                    .addComponent(fweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb6)
                    .addComponent(fm)
                    .addComponent(ff)
                    .addComponent(user_lb7)
                    .addComponent(fblood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb8)
                    .addComponent(user_lb9)
                    .addComponent(fcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb10)
                    .addComponent(fqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_lb12)
                    .addComponent(faadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_lb11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(forg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ffnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffnameActionPerformed

    private void flnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flnameActionPerformed

    private void fdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdobActionPerformed

    private void fcontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcontActionPerformed

    private void fqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fqtyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Query="";
Connection c;
Statement s;
ResultSet r;
String mname="";
String fname=ffname.getText();
mname=fmname.getText();
String lname=flname.getText();
String email=femail.getText();
String dob=fdob.getText();
String weight=fweight.getText();
String gender="";
    if(ff.isSelected())
        gender="F";
    if(fm.isSelected())
        gender="M"; 
String blood=fblood.getSelectedItem().toString();
String cont=fcont.getText();
String add=fadd.getText();
String qty=fqty.getText();
int id=0;
if(Integer.parseInt(qty)>500){
    JOptionPane.showMessageDialog(this, "Quantity Should be less then 500ml..");
    return;
}
String aadhar=faadhar.getText();
String org=forg.getSelectedItem().toString();
try
{    
    Class.forName("java.sql.Driver");
    c=DriverManager.getConnection("jdbc:mysql://localhost/BloodDonation", "root", "gaurav");
    s=c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
    r=s.executeQuery("Select max(donor_id) from blood_donor");
    
    
    if(r.next()) id=r.getInt(1)+1;  else id=1;
    r=s.executeQuery("Select donor_id from blood_donor where aadhar ="+faadhar.getText());
    
    
    if(r.next()){
        Query="insert into store values('"+r.getInt(1)+"','"+qty+"',Date(Now()),'"+org+"')";
        s.executeUpdate(Query);
    }else{
        Query="insert into blood_donor values('"+fname+"','"+mname+"','"+lname+"','"+email+"','"+dob+"','"+weight+"','"+gender+"','"+blood+"','"+cont+"','"+add+"','"+aadhar+"',"+id+")";
        s.executeUpdate(Query);
        Query="insert into store values('"+id+"','"+qty+"',Date(Now()),'"+org+"')";
        s.executeUpdate(Query);
    }
    
    //add in avail
    r=s.executeQuery("Select * from avail where blood_group='"+blood+"' && org='"+org+"'");
    if(r.next()){
        Query="update avail set Qty=Qty+"+qty+" where blood_group='"+blood+"' && org='"+org+"'";
        s.executeUpdate(Query);
    }else{
        Query="insert into avail values('"+blood+"','"+qty+"','"+org+"')";
        s.executeUpdate(Query);
    }        
    JOptionPane.showMessageDialog(this, "Sucessfuly Submited..!!!");
    new main().setVisible(true);
    this.setVisible(false);
}catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Something Wrong..!!!"+e);return;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(don.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new don().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField faadhar;
    private javax.swing.JTextField fadd;
    private javax.swing.JComboBox fblood;
    private javax.swing.JTextField fcont;
    private javax.swing.JTextField fdob;
    private javax.swing.JTextField femail;
    private javax.swing.JRadioButton ff;
    private javax.swing.JTextField ffname;
    private javax.swing.JTextField flname;
    private javax.swing.JRadioButton fm;
    private javax.swing.JTextField fmname;
    private javax.swing.JComboBox forg;
    private javax.swing.JTextField fqty;
    private javax.swing.JTextField fweight;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel user_lb;
    private javax.swing.JLabel user_lb1;
    private javax.swing.JLabel user_lb10;
    private javax.swing.JLabel user_lb11;
    private javax.swing.JLabel user_lb12;
    private javax.swing.JLabel user_lb2;
    private javax.swing.JLabel user_lb3;
    private javax.swing.JLabel user_lb4;
    private javax.swing.JLabel user_lb5;
    private javax.swing.JLabel user_lb6;
    private javax.swing.JLabel user_lb7;
    private javax.swing.JLabel user_lb8;
    private javax.swing.JLabel user_lb9;
    // End of variables declaration//GEN-END:variables
}
