/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class forget extends javax.swing.JFrame {

    /**
     * Creates new form forget
     */
    public forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_lb = new javax.swing.JLabel();
        ffname = new javax.swing.JTextField();
        user_lb2 = new javax.swing.JLabel();
        flname = new javax.swing.JTextField();
        fdob = new javax.swing.JTextField();
        fuser = new javax.swing.JTextField();
        user_lb1 = new javax.swing.JLabel();
        pass_lb2 = new javax.swing.JLabel();
        ff = new javax.swing.JRadioButton();
        fm = new javax.swing.JRadioButton();
        pass_lb3 = new javax.swing.JLabel();
        pass_lb6 = new javax.swing.JLabel();
        fmobile = new javax.swing.JTextField();
        pass_lb5 = new javax.swing.JLabel();
        femail = new javax.swing.JTextField();
        pass_lb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user_lb.setBackground(new java.awt.Color(255, 255, 255));
        user_lb.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        user_lb.setForeground(new java.awt.Color(0, 0, 153));
        user_lb.setText("First Name");

        ffname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        user_lb2.setBackground(new java.awt.Color(255, 255, 255));
        user_lb2.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        user_lb2.setForeground(new java.awt.Color(0, 0, 153));
        user_lb2.setText("Last Name");

        flname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        fdob.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        fuser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        user_lb1.setBackground(new java.awt.Color(255, 255, 255));
        user_lb1.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        user_lb1.setForeground(new java.awt.Color(0, 0, 153));
        user_lb1.setText("Username");

        pass_lb2.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb2.setFont(new java.awt.Font("AR ESSENCE", 0, 18)); // NOI18N
        pass_lb2.setForeground(new java.awt.Color(204, 0, 0));
        pass_lb2.setText("YYYYMMDD");

        ff.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ff.setText("F");

        fm.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        fm.setText("M");

        pass_lb3.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb3.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        pass_lb3.setForeground(new java.awt.Color(0, 0, 153));
        pass_lb3.setText("Gender");

        pass_lb6.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb6.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        pass_lb6.setForeground(new java.awt.Color(0, 0, 153));
        pass_lb6.setText("Mobile");

        fmobile.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        pass_lb5.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb5.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        pass_lb5.setForeground(new java.awt.Color(0, 0, 153));
        pass_lb5.setText("Email");

        femail.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        pass_lb1.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb1.setFont(new java.awt.Font("AR ESSENCE", 0, 24)); // NOI18N
        pass_lb1.setForeground(new java.awt.Color(0, 0, 153));
        pass_lb1.setText("DOB");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Forget");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_lb)
                            .addComponent(user_lb1)
                            .addComponent(pass_lb3)
                            .addComponent(pass_lb5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ffname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(user_lb2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fuser, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(fm)
                                                .addGap(45, 45, 45)
                                                .addComponent(ff)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pass_lb6)
                                            .addComponent(pass_lb1))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fdob, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pass_lb2))
                                    .addComponent(flname, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(femail, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb)
                    .addComponent(ffname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_lb2)
                    .addComponent(flname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb1)
                    .addComponent(fuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_lb1)
                    .addComponent(fdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_lb2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_lb6)
                    .addComponent(pass_lb3)
                    .addComponent(fm)
                    .addComponent(ff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_lb5)
                    .addComponent(femail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Query="";
        Connection c;
        Statement s;
        ResultSet r;
        String fname=ffname.getText();
        String lname=flname.getText();
        String dob=fdob.getText();
        String gender="";
        if(ff.isSelected())
        gender="F";
        if(fm.isSelected())
        gender="M";
        String mobile=fmobile.getText();
        String email=femail.getText();        
            try
            {
                Query="Select fname,lname,dob,gender,mobile,email,pass from register where username='"+fuser.getText()+"'";
                System.err.println(Query);
                Class.forName("java.sql.Driver");
                c=DriverManager.getConnection("jdbc:mysql://localhost/BloodDonation", "root", "gaurav");
                s=c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
                r =s.executeQuery(Query);
                if(r.next()){
                    if(fname.equalsIgnoreCase(r.getString(1)) && lname.equalsIgnoreCase(r.getString(2)) && dob.equalsIgnoreCase(r.getString(3).replace("-", "")) && gender.equalsIgnoreCase(r.getString(4)) && mobile.equalsIgnoreCase(r.getString(5)) && email.equalsIgnoreCase(r.getString(6)) )
                    {    JOptionPane.showMessageDialog(this, r.getString(1)+" "+r.getString(2)+" Your Password is : "+r.getString(7));
                        new login().setVisible(true);
                    this.setVisible(false);
                    }
                    else
                        JOptionPane.showMessageDialog(this, "Enter Valid Details...!!!");
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No Record Found..!!!");
                }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Something Wrong..!!!"+e);return;
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forget.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forget().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fdob;
    private javax.swing.JTextField femail;
    private javax.swing.JRadioButton ff;
    private javax.swing.JTextField ffname;
    private javax.swing.JTextField flname;
    private javax.swing.JRadioButton fm;
    private javax.swing.JTextField fmobile;
    private javax.swing.JTextField fuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel pass_lb1;
    private javax.swing.JLabel pass_lb2;
    private javax.swing.JLabel pass_lb3;
    private javax.swing.JLabel pass_lb5;
    private javax.swing.JLabel pass_lb6;
    private javax.swing.JLabel user_lb;
    private javax.swing.JLabel user_lb1;
    private javax.swing.JLabel user_lb2;
    // End of variables declaration//GEN-END:variables
}
