/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Gaurav
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_lb = new javax.swing.JLabel();
        pass_lb = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        reg_lb = new javax.swing.JLabel();
        for_lb = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        user_lb.setBackground(new java.awt.Color(255, 255, 255));
        user_lb.setFont(new java.awt.Font("AR ESSENCE", 0, 28)); // NOI18N
        user_lb.setForeground(new java.awt.Color(0, 0, 153));
        user_lb.setText("Username");

        pass_lb.setBackground(new java.awt.Color(255, 255, 255));
        pass_lb.setFont(new java.awt.Font("AR ESSENCE", 0, 28)); // NOI18N
        pass_lb.setForeground(new java.awt.Color(0, 0, 153));
        pass_lb.setText("Password");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        reg_lb.setBackground(new java.awt.Color(0, 0, 0));
        reg_lb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        reg_lb.setForeground(new java.awt.Color(25, 118, 211));
        reg_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reg_lb.setText("Register");
        reg_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_lbMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_lbMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_lbMouseClicked(evt);
            }
        });

        for_lb.setBackground(new java.awt.Color(0, 0, 0));
        for_lb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        for_lb.setForeground(new java.awt.Color(25, 118, 211));
        for_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        for_lb.setText("Forget Password ?");
        for_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        for_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                for_lbMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                for_lbMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                for_lbMouseClicked(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_lb)
                            .addComponent(pass_lb))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(reg_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(for_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_lb)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_lb)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reg_lb)
                    .addComponent(for_lb))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseExited
        reg_lb.setForeground(new Color(27, 153, 229));
        reg_lb.setFont(new Font("Aparajita", Font.PLAIN, 18));
    }//GEN-LAST:event_reg_lbMouseExited

    private void reg_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseEntered
        reg_lb.setForeground(new Color(39, 174, 96));
        reg_lb.setFont(new Font("Aparajita", Font.BOLD, 20));
    }//GEN-LAST:event_reg_lbMouseEntered

    private void reg_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseClicked
        this.setVisible(false);
        new register().setVisible(true);
    }//GEN-LAST:event_reg_lbMouseClicked

    private void for_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseExited
        for_lb.setForeground(new Color(27, 153, 229));
        for_lb.setFont(new Font("Aparajita", Font.PLAIN, 18));
    }//GEN-LAST:event_for_lbMouseExited

    private void for_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseEntered
        for_lb.setForeground(Color.red);
        for_lb.setFont(new Font("Aparajita", Font.BOLD, 19));
    }//GEN-LAST:event_for_lbMouseEntered

    private void for_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseClicked
        this.setVisible(false);
        new forget().setVisible(true);
    }//GEN-LAST:event_for_lbMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String Query="Select Pass,fname,lname from register where username='"+jTextField1.getText()+"'";
Connection c;
Statement s;
ResultSet r;
try
 {
     Class.forName("java.sql.Driver");  
     c=DriverManager.getConnection("jdbc:mysql://localhost/BloodDonation", "root", "gaurav"); 
     s=c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
     r =s.executeQuery(Query);
     if(r.next()){
        if(r.getString(1).equals(jPasswordField1.getText())){         
            JOptionPane.showMessageDialog(this, "Welcome "+r.getString(2)+" "+r.getString(3)+"..!!");
            new menu().setVisible(true);
            this.setVisible(false);
        }
        else
            JOptionPane.showMessageDialog(this, "Invalid Password.!!");
     }
     else
     {
         JOptionPane.showMessageDialog(this, "Not Registered Yet..!!!\nRegster Yourself First..");
     }
 }catch(Exception e)
 {
     JOptionPane.showMessageDialog(this, "Something Wrong..!!!");
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel for_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel pass_lb;
    private javax.swing.JLabel reg_lb;
    private javax.swing.JLabel user_lb;
    // End of variables declaration//GEN-END:variables
}
