/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Gaurav
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        reg_lb = new javax.swing.JLabel();
        for_lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Who NEEDS BLOOD The need of blood is great. On any given day, an average \nof 34,000 units of blood are needed to save precious human lives from accidentand bums, heart surgery, organ transplants & patients receiving \ntreatment for leukemia, cancer & other diseases...\n\nBlood ...it runs in our veins and plays a vital role in the body mechanism.But have you ever spared a thought for those who are fighting with some disease and need bloodurgently. Act now and donate your blood without any worry. It won't cost you a thing but could bring back the smile on \nsomeone's face.");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 610, 250));

        reg_lb.setBackground(new java.awt.Color(0, 0, 0));
        reg_lb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        reg_lb.setForeground(new java.awt.Color(25, 118, 211));
        reg_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reg_lb.setText("Register");
        reg_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reg_lbMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reg_lbMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reg_lbMouseClicked(evt);
            }
        });
        getContentPane().add(reg_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 11, 90, -1));

        for_lb.setBackground(new java.awt.Color(0, 0, 0));
        for_lb.setFont(new java.awt.Font("Aparajita", 0, 18)); // NOI18N
        for_lb.setForeground(new java.awt.Color(25, 118, 211));
        for_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        for_lb.setText("Login");
        for_lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        for_lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                for_lbMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                for_lbMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                for_lbMouseClicked(evt);
            }
        });
        getContentPane().add(for_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(857, 11, 67, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/b.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reg_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseExited
        reg_lb.setForeground(new Color(27, 153, 229));
        reg_lb.setFont(new Font("Aparajita", Font.PLAIN, 18));
    }//GEN-LAST:event_reg_lbMouseExited

    private void reg_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseEntered
        reg_lb.setForeground(new Color(39, 174, 96));
        reg_lb.setFont(new Font("Aparajita", Font.BOLD, 20));
    }//GEN-LAST:event_reg_lbMouseEntered

    private void reg_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reg_lbMouseClicked
        this.setVisible(false);
        new register().setVisible(true);
    }//GEN-LAST:event_reg_lbMouseClicked

    private void for_lbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseExited
        for_lb.setForeground(new Color(27, 153, 229));
        for_lb.setFont(new Font("Aparajita", Font.PLAIN, 18));
    }//GEN-LAST:event_for_lbMouseExited

    private void for_lbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseEntered
        for_lb.setForeground(Color.blue);
        for_lb.setFont(new Font("Aparajita", Font.BOLD, 19));
    }//GEN-LAST:event_for_lbMouseEntered

    private void for_lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_for_lbMouseClicked
        this.setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_for_lbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel for_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel reg_lb;
    // End of variables declaration//GEN-END:variables
}
